### ISSUE TITLE
Support `git stash show --stat --patch`

### ISSUE THREAD

**Issue by gibfahn** [dandavison/delta#100]
Looks like `git stash show` doesn't get formatted by delta:

<img width="341" alt="image" src="https://user-images.githubusercontent.com/15943089/74733529-6c830100-5244-11ea-9e6e-8bed110154ff.png">

Using `delta 0.0.16` on macOS.

### Script to reproduce

```shell
export GIT_PAGER='delta --theme=TwoDark'
mkdir tst
cd tst
git init
printf "bar\nbaz\n" >foo_diff
printf "bar\nbaz\n" >foo_stash

git add foo*
git commit -m "Initial Commit"

printf "bat\n" >> foo_stash
git stash
printf "bat\n" >> foo_diff

git diff # Works with delta
git stash show # Doesn't.
```

**Comment by dandavison** [comment]
Hi @gibfahn I believe you have  something like this in your git configuration, right?

```
[stash]
    showStat = true
    showPatch = true
```

I say that because, with out-of-the-box git, I'm seeing reasonable behaviour from delta with git stash:

![image](https://user-images.githubusercontent.com/52205/75650701-5732ad00-5c1c-11ea-8f79-7fa7a14c7263.png)

However, I definitely agree that what you point out is a bug: i.e. that when the `stat` and `patch` outputs are combined, delta fails to recognise the patch:

![image](https://user-images.githubusercontent.com/52205/75650760-847f5b00-5c1c-11ea-827d-832a479970a6.png)

It's fairly clear what the issue is. We [peek at the first line](https://github.com/dandavison/delta/blob/master/src/delta.rs#L186) to see if we recognise the type of input, see `foo_stash | 1 +`, don't recognise that, and thereafter never attempt to parse anything. So it seems that one solution would be to keep trying to recognise sections, even after we initially haven't recognised the type of input.

There is an underlying problem here: while I'm OK with most of delta's code, the [state machine parser](https://github.com/dandavison/delta/blob/master/src/delta.rs#L53-L189) needs to be rewritten!

**Comment by gibfahn** [comment]
> Hi @gibfahn I believe you have something like this in your git configuration, right?
> 
> [stash]
>     showStat = true
>     showPatch = true

Ahh yeah, I should have thought of that, I tend to forget how much I have in my git config...


>So it seems that one solution would be to keep trying to recognise sections, even after we initially haven't recognised the type of input.

Seems reasonable

>There is an underlying problem here: while I'm OK with most of delta's code, the state machine parser needs to be rewritten!

That seems like a fairly large challenge 😁 . If I get some time I might take a look, but no guarantees.

**Comment by dandavison** [comment]
> That seems like a fairly large challenge 😁 . If I get some time I might take a look, but no guarantees.

Yes, tbh it's probably something I'm going to want to have a go at -- I'll feel bad if I leave it in its current state for long and it's making it hard to fix bugs like this.
