### ISSUE TITLE
🐛 Running delta with no args doesn't print anything, can't be exited with CTRL-c

### ISSUE THREAD

**Issue by mario-grgic** [dandavison/delta#1039]
Running delta 0.12.1 built with rustc 1.59.0 (9d1b2106e 2022-02-23)on macOS Catalina 10.15.7 does not print any output. Furthermore, delta can't be killed with CTRL-c. The only way to exit it is to suspend it (with CTRL-z), or to kill it from another shell.

**Comment by mario-grgic** [comment]
Note that specifying argument (files to diff), or other options works normally.

**Comment by dandavison** [comment]
Thanks @mario-grgic, I agree that something's wrong. I hadn't realized it was behaving like that. It's expected that it does nothing and doesn't print any output, because it's waiting for input on stdin. But we should be able to kill it with ctrl-c. Delta has a similar architecture to bat in the way that it invokes a child pager process and accepts stdin; but bat with no arguments exits cleanly on ctrl-c when it's waiting for input.

**Comment by mario-grgic** [comment]
I used git bisect to find first commit where `CTRL-c` can't interrupt the process. The change was introduced in commit 55287a827e8f2527df938a1b85e23290f8692607

```
55287a827e8f2527df938a1b85e23290f8692607 is the first bad commit
commit 55287a827e8f2527df938a1b85e23290f8692607
Author: Dan Davison <dandavison7@gmail.com>
Date:   Tue Mar 1 08:53:51 2022 -0500

    Run in diff mode iff two positional arguments are supplied
    
    Fixes #989

 src/main.rs             | 23 +++++++++++++++--------
 src/subcommands/diff.rs | 19 ++++---------------
 2 files changed, 19 insertions(+), 23 deletions(-)
```

**Comment by mario-grgic** [comment]
In that commit, pressing `CTRL-c' prints:

```
:...skipping...
```

and the process does not exit.

**Comment by alock** [comment]
Any plan to release this in a new version?

**Comment by dandavison** [comment]
@alock, thanks, doing that now.

**Comment by dandavison** [comment]
New version is released.

**Comment by alock** [comment]
Really thank you!  Works great btw.
