### ISSUE TITLE
🐛 Incorrect output when grepping in a branch with "/" and "-" in the name

### ISSUE THREAD

**Issue by cffswb** [dandavison/delta#1083]
## Context

OS: Linux
Delta revision: 427c9aa971f3

## Description

Tested in `delta` repository.

Run `git grep` alone:
`$ GIT_CONFIG_GLOBAL=/dev/null git grep theme origin/gh-pages`
![image](https://user-images.githubusercontent.com/6070469/169503081-b74fc203-6ef6-44c6-9153-8fcdf769a50f.png)

Run `git grep` + `delta`:
`$ GIT_CONFIG_GLOBAL=/dev/null git -c pager.grep='delta --no-gitconfig' grep theme origin/gh-pages`
![image](https://user-images.githubusercontent.com/6070469/169503181-5b4370e7-47ed-44da-9a59-e663d12d4aeb.png)
The `gh-pages`es become `gh:pages`es, and the `theme`s aren't highlighted.

**Comment by dandavison** [comment]
Thanks @cffswb, will look into this.

By the way, until this is fixed, I just want to mention that piping `rg --json` into delta should never have parsing bugs (since delta receives a JSON format rather than having to parse grep output, which can't be parsed unambiguously, although I don't think we should be confusing an internal `-` character in a file name if that's what's happening here)

**Comment by mvf** [comment]
This seems to also affect paths whose element just above the file has a `-` in it. Here's a shot of `git grep hostmakedepends` from the root of https://www.github.com/void-linux/void-packages. `cyrus-sasl` and `d-feet` are mangled:

![delta2](https://user-images.githubusercontent.com/304760/195181464-cc017e2f-ed04-470e-9199-93905e47ff85.png)

The same command from the `srcpkgs` directory leaves `d-feet` intact, but the highlighting isn't applied anymore:

![delta](https://user-images.githubusercontent.com/304760/195180245-2c36496f-8d3f-4b31-9e38-9559de8bcf46.png)

This seems to happen when the path element with the `-` comes first and only has a single character before the first `-`.

**Comment by dandavison** [comment]
Hi all, currently the best answer here is to use `rg --json` to avoid any parse errors. Fundamentally the issue here is that traditional grep output is not unambiguously parseable. It would be nice if someone added JSON output to `git grep`. Copying from the other dup issues #1631 and #1259:

The delta manual contains an entry addressing this:

> If you don't need special features of git grep, then for best results pipe rg --json output to delta: this avoids parsing ambiguities that are inevitable with the output of git grep and grep.

See the ~500 lines of unit tests here: https://github.com/dandavison/delta/blob/main/src/handlers/grep.rs#L653-L1177. If someone can improve the parsing while keeping all those tests passing (and hopefully adding a test for what you're fixing) that would be fantastic.


I'm going to close this since I have personally taken a fairly large stab at it and also implemented `rg --json` support for a fully robust solution.

**Comment by dandavison** [comment]
@joshtriplett I think that's a good idea! I had thought that git would refuse to deliver the color escape codes when sending output to its pager, but it looks like it does, as can be verified with

```
GIT_PAGER='bat --plain -A' git grep foo
```

> the recommended delta configuration could include turning on color for grep

It seems that `git grep` has color enabled by default, right?

**Comment by joshtriplett** [comment]
@dandavison Yes, grep and other commands use color by default unless disabled.

**Comment by joshtriplett** [comment]
@dandavison Fixed: https://github.com/dandavison/delta/pull/1634
