### ISSUE TITLE
🐛 Escape chars rendered incorrectly when invoked directly

### ISSUE THREAD

**Issue by FallenGameR** [dandavison/delta#1139]
Environment: Windows11 & pwsh & less is setup to use -IeFRX by default

When delta is used via git all is fine. But when delta is invoked to diff two files it shows all escape chars via their codes. I found out that Specifying $env:DELTA_PAGER to some incorrect value actually causes delta to pick up the right way to render escape chars:

```
D:\src\rust\quickreplace [ALEXKO-11]
» delta .\Cargo.toml .\Cargo.toml.new
warning: in the working copy of 'quickreplace/./Cargo.toml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'quickreplace/./Cargo.toml.new', LF will be replaced by CRLF the next time Git touches it

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<U+25B6><U+FE0F> MOD ./Cargo.toml <U+27F6>   ./Cargo.toml.new
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  1 <U+22EE>  1 │[package]
  2 <U+22EE>    │name = "quickreplace"
    <U+22EE>  2 │NAME = "quickreplace"
  3 <U+22EE>  3 │version = "0.1.0"
  4 <U+22EE>  4 │edition = "2021"
  5 <U+22EE>  5 │
D:\src\rust\quickreplace [ALEXKO-11]
» $env:DELTA_PAGER = "0"  
D:\src\rust\quickreplace [ALEXKO-11] 
» delta .\Cargo.toml .\Cargo.toml.new
warning: in the working copy of 'quickreplace/./Cargo.toml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'quickreplace/./Cargo.toml.new', LF will be replaced by CRLF the next time Git touches it

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
▶️ MOD ./Cargo.toml ⟶   ./Cargo.toml.new
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  1 ⋮  1 │[package]
  2 ⋮    │name = "quickreplace"
    ⋮  2 │NAME = "quickreplace"
  3 ⋮  3 │version = "0.1.0"
  4 ⋮  4 │edition = "2021"
  5 ⋮  5 │
D:\src\rust\quickreplace [ALEXKO-11]
» $env:less
-IeFRX
```

**Comment by dandavison** [comment]
Hi @FallenGameR, delta users often see a problem like this on Windows. It's because git bundles its own (not broken) version of less, but when used without git, delta picks up a broken version of less. So the solution is to ensure delta finds a recent, not broken version of less. You should be able to find the executable that git is using with this trick I think:

```
git -c core.pager='which less' show
```

**Comment by FallenGameR** [comment]
Here is the output from git and two versions of less that pwsh is able to find on PATH. I'm not sure how git resolves the less.exe it uses though since in the git output I see a UNIX path that is not valid on Windows. Both instances of less.exe that pwsh finds say they are of the same 590 version but say that they resolve regular expressions with different engines):

```

» git -c core.pager='which less' show
/usr/bin/less

» gcm less

CommandType     Name         Version    Source
-----------     ----         -------    ------
Application     less.exe     1.0.0.0    C:\ProgramData\chocolatey\bin\less.exe
Application     less.exe     0.0.0.0    C:\Program Files\Git\usr\bin\less.exe

» C:\ProgramData\chocolatey\bin\less.exe --version
less 590 (Spencer V8 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less

» & "C:\Program Files\Git\usr\bin\less.exe" --version
less 590 (PCRE regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

If I change delta pager to use the second less that pwsh finds (the one from git) ```$env:DELTA_PAGER = "C:\Program Files\Git\usr\bin\less.exe"``` then the escape chars are fixed when delta is invoked directly. But at the same time when delta is used via 'git show' less.exe doesn't stop in the interactive scrolling mode when output doesn't fit the console screen.

**Comment by dandavison** [comment]
> Both instances of less.exe that pwsh finds say they are of the same 590 version

Yep, I'm not sure exactly what's going on, but most Windows users report that they have broken less versions in their system. I believe that's why git bundles it. think you're doing the right thing -- either use git's less, or install it yourself from the less website.

> If I change delta pager to use the second less that pwsh finds (the one from git) `$env:DELTA_PAGER = "C:\Program Files\Git\usr\bin\less.exe"` then the escape chars are fixed when delta is invoked directly.

Is it invoking a pager, or is all the output simply being dumped to standard output?  

> But at the same time when delta is used via 'git show' less.exe doesn't stop in the interactive scrolling mode when output doesn't fit the console screen.

Right, so there are two things that need to be true:

1. A non-broken less executable is being invoked
2. The correct arguments are being passed to less

There are various ways to achieve (1) and (2) as you know: there's the env vars `GIT_PAGER` and `DELTA_PAGER`, with which you can set the executable and the command line flags, and there's also the env var `LESS` with which one can set flags for less to use.

I'll close this issue, since there aren't any delta bugs involved. However, I would appreciate any improvements to the documentation for Windows users since (as you can see in the issue history!) issues with less and incorrect rendering of utf-8 / ANSI escapes are common on Windows.
