### ISSUE TITLE
Improve within-line edit inference defaults

### ISSUE THREAD

**Issue by igordovgaluk** [dandavison/delta#119]
In some cases, delta not highlights within-line changes. Just a few of the examples:
![image](https://user-images.githubusercontent.com/4215041/78371536-c65f4080-75d0-11ea-8a07-598a6f2501fc.png)

![image](https://user-images.githubusercontent.com/4215041/78372065-7b91f880-75d1-11ea-8668-6d93eefcb3e2.png)

Although few lines above/below of the same file the within-line changes are highlighted.

Not expected for me as a user.

**Comment by dandavison** [comment]
Hi @igordovgaluk, thanks, this is probably an area in which delta can do better.

The key flag here is `--max-line-distance`. You could experiment with that and see whether you can find a value that gives good results for you. For example, try `--max-line-distance 0.6`.

The basic issue is that delta is trying to avoid false positives as well as false negatives. So in order to highlight changed substrings, it first demands that the lines are sufficiently similar. That is what  `--max-line-distance` controls.

delta tokenizes before aligning strings, so it performs the alignment on the tokens rather than character by character. So the issue is that in your first example, the two lines are more different than they are similar, because there is a long token that differs (`g_themeController` vs `g_themeViewModel`) in a relatively short line.

I'm definitely open to suggestions regarding changing the default (or the algorithm). But of course we are trying to handle all possible languages.

```
--max-line-distance <max_line_distance>                                             
    The maximum distance between two lines for them to be inferred to
    be homologous. Homologous line pairs are highlighted according to
    the deletion and insertion operations transforming one into the
    other. [default: 0.3]
```

**Comment by dandavison** [comment]
@igordovgaluk thanks for opening this; it was very helpful. Another issue has been opened addressing this same topic which has more discussion now. Let's move all conversation to #140.
