### ISSUE TITLE
🐛 grep --heading output is incorrect

### ISSUE THREAD

**Issue by chulkilee** [dandavison/delta#1197]
delta replaces `-` with `:` on the file heading when using `grep --heading`.

Please see the following steps to reproduce it. Tested on git-delta 0.14.0 (installed with homebrew)

```
# set up
git init
mkdir -p foo/bar-dash/hello
echo "hello world" > foo/bar-dash/hello/a.txt
git add foo

# grep with no-pager
git --no-pager grep hello
foo/bar-dash/hello/a.txt:hello world

# grep - OK
git grep hello
foo/bar-dash/hello/a.txt:hello world

# grep with --heading
git --no-pager grep --heading hello
foo/bar-dash/hello/a.txt
hello world

# grep with --heading - NOT OK
git grep --heading hello
foo/bar:dash/hello/a.txt
hello world
```

**Comment by dandavison** [comment]
Hi @chulkilee, thanks for this. I haven't yet thought through your example. However I just want to mention quickly: have you tried `rg --json | delta`? That is the only grep method that should be fully correct with delta. The reason is that the JSON format from ripgrep is unambiguously parseable, but all other grep formats contain parsing ambiguities, e.g. when file names contain characters such as `-` and `:` used as field delimiters.

**Comment by chulkilee** [comment]
With rg

```
# rg
rg hello
foo/bar-dash/hello/a.txt
1:hello world

# rg json to delta
rg hello --json | delta
foo/bar-dash/hello/a.txt:1:hello world
```

I guess there is a missing case in [the grep handler](https://github.com/dandavison/delta/blob/0.14.0/src/handlers/grep.rs)?

**Comment by Daghall** [comment]
The same is true with the `-l`/`--files-with-matches` and `-L`/`--files-without-match`:

```
git grep -l hello
foo/bar:dash/hello/a.txt
```

The first `-` in the path is replaced with a `:`.

**Comment by dandavison** [comment]
Thanks @chulkilee @Daghall, for fully correct grep output coloring with delta, use `rg --json ... | delta`

I'd be happy for people to submit PRs improving the parsing in the grep handler, but I don't believe it's possible for it to be fully correct with `grep`, `git grep` etc since their output is not machine-parseable: there are ambiguities about what is part of a file and what is a separator. (In theory an alternative would be to contribute a JSON output option to `git grep`)

@chulkilee 

> With rg

Can you explain the example output you posted? Do you agree it's correct with `rg --json`?

**Comment by dandavison** [comment]
@chulkilee I think delta actually already has a test case acknowledging (by an `[ignore]` marker and a comment) that it cannot handle your example. Is that right, is this the bug you're reporting?

https://github.com/dandavison/delta/blob/db0a9cffda699d1aa61d53c0aea1e3fea80c066c/src/handlers/grep.rs#L639-L643

**Comment by Daghall** [comment]
@dandavison, yes, the symptom of that test seems to be the same as our examples.

I'm not sure I can help you fix this. I'll make a pull-request if I have a breakthrough. 🙂

**Comment by dandavison** [comment]
@Daghall thanks! Yes you can probably see from the existing test cases and regexes that it's a bit challenging to improve.

**Comment by chulkilee** [comment]
@dandavison `rg --json | delta` is correct. Just wanted to show the output

Just my 2 cents:

* Ideally, `git grep` should support `--porcelain` option for this purpose.
* Or, `git grep` supports `-z --heading` correctly, so that we can split path and others by NULL (currently `-z` seems to be ignored when `--heading` is set)
* Or git passes git options down to a pager so that the pager can be "smarter". Not sure that's available. (e.g. `GIT_GREP_OPTIONS=...`
* If various git output can be handled with delta, we may add `delta --git` option to give the hint.. but I'm not sure how different git outputs are with different options.

**Comment by dandavison** [comment]
Thanks, those suggestions sound right to me @chulkilee. I've added some clarification to the manual that `rg --json | delta` is the only grep handler that can be fully correct, and I've closed this since the main paths forwards involve contributing to git rather than delta.
