### ISSUE TITLE
🐛 input redirection doesn't work for the standalone delta command?

### ISSUE THREAD

**Issue by unphased** [dandavison/delta#1219]
```
❯ delta <(echo abc) <(echo abd)   

2/proc/self/fd/13:1:
  1¦   │pipe:[212694280]
\ No newline at end of file
   ¦  1│pipe:[212694281]
\ No newline at end of file
```

**Comment by dandavison** [comment]
Hi @unphased, this does work for me on MacOS delta 0.14.0 under zsh 5.8.1 and bash 5.1.16 and bash 3.2.57. What's your OS?

In some previous versions of delta it did not work, because `delta /path/to/file_A /other/path/to/file_B` is really `git diff --no-index /path/to/file_A /other/path/to/file_B` under the hood, and git doesn't support reading from files or pseudo-files created by process substitution (on any OSs as far as I know, but I think the details of process substitution differ across OSs).

**Comment by unphased** [comment]
That's really nice to know it's been addressed in newer versions! I'm on the old v0.11.2 on this particular linux box, will update.

**Comment by unphased** [comment]
Just updating that `rustup update && cargo install git-delta` definitely did the trick

**Comment by C0Florent** [comment]
Weirdly enough, I've noticed this bug too, although I'm using more recent versions.

It first happened to me on my personal laptop running NixOS 24.11, as well as more recent unstable (can't check right now), running bash 5.2.37 and delta 0.18.2 (these versions might be wrong because once again, I can't check right now). That time I believed it was a bash limitation that you can't use more than one input redirection in a single command and left it at that.

I've noticed this bug again at work today, running delta 0.18.2 with bash 5.2.37 on Windows 11 (bash provided by Git Bash).

Here's what I'm getting:

```
(0) $ PS1='($?) \$ '
(0) $ delta <(echo abc) <(echo abd)
(1) $ delta --version
delta 0.18.2
(0) $ "$SHELL" --version
GNU bash, version 5.2.37(1)-release (x86_64-pc-msys)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
(0) $ 
```

As you can see, delta exits 1 silently, no error message to be found.
Do you have any idea what would cause this ?
