### ISSUE TITLE
🚀 ability to apply hunks in side-by-side diff view

### ISSUE THREAD

**Issue by rootex-** [dandavison/delta#1305]
Hi, 

🚀  it would be great to add an ability to apply hunks in side-by-side diff view (like, e.g., IntelliJ IDEA can).

![intellij-idea-diff-view](https://user-images.githubusercontent.com/8237030/219645747-cf8acd20-ef56-48dd-8400-1227cdf34c55.png)

E.g.: Hunk from the right side can be applied to the left using an arrow << (see the double arrows >> and << for that). Arrows can be triggered by keybindings. 
 
This will be a top-notch feature making it easier to modify files on the fly in diff view.

**Comment by nagromc** [comment]
Well, the description states that Delta is "a syntax-highlighting pager for git, diff, and grep output". It is not meant to change the code or to stage files. For that purpose, I would suggest [GitUI](https://github.com/extrawurst/gitui), which is also written in Rust.

**Comment by dandavison** [comment]
Thanks @nagromc, that's correct. If you are prepared to have a running Emacs instance then I can also recommend Magit with https://github.com/dandavison/magit-delta.

**Comment by rootex-** [comment]
> Well, the description states that Delta is "a syntax-highlighting pager for git, diff, and grep output". It is not meant to change the code or to stage files. For that purpose, I would suggest [GitUI](https://github.com/extrawurst/gitui), which is also written in Rust.

Well, gitui does not provide this functionality, see the feature request: https://github.com/extrawurst/gitui/issues/1294

**Comment by extrawurst** [comment]
Thanks for the honorable mention of gitui here.
I still did not have time to investigate this but I hope eventually we can use delta as the general lib to calculate the diffs that gitui shows. right now this is done based on libgit2 diffing. I am expecting to be able to pass a two buffers in and receive annotations out that I can use to visualise the diffs either side by side or unified depending on the users taste.

since gitui supports staging/reverting on line-by-line basis using the annotated output to stage/unstage hunks and individual lines should smoothly integrate. it was just not tackled by anyone yet. 

Collaborations welcome 💪

**Comment by dandavison** [comment]
Hi @extrawurst, no unfortunately there's no ETA on librarification.
