### ISSUE TITLE
🐛 delta breaks git log

### ISSUE THREAD

**Issue by neo-apz** [dandavison/delta#1386]
I'm experiencing an issue when running `git log` that causes the command to keep producing output and because there are many commits on my branch, the command just keeps printing. It seems no pagination is happening. Everything else works great and only this is causing an issue.

**Comment by dandavison** [comment]
Hi @neo-apz, delta tries to invoke a pager automatically. By default is tries to use `less`, but if you have an environment variable set such as `PAGER=` or `PAGER=cat` then you'd see the behaviour you describe. Can you post

- your OS
- `which less`
- `env | grep -i pager`

I'm converting this to a Discussion because it's not a bug or feature request.
