### ISSUE TITLE
how do i turn off syntax highlighting?

### ISSUE THREAD

**Issue by iomintz** [dandavison/delta#14]
I don't like syntax highlighting. Is there a way I can turn it off?

**Comment by dandavison** [comment]
> Is there a way I can turn it off?

Not yet, but thanks, this makes sense and should exist.

**Comment by iomintz** [comment]
Well, this "works", but I'm not really sure how to fix the background coloring for added/deleted lines.
![screenshot of hard to read highlighting](https://user-images.githubusercontent.com/538336/65994880-ed8a5900-e459-11e9-8fc8-5332b0aee76b.png)

**Comment by dandavison** [comment]
Hm, let's get that sorted out. As you saw, delta now accepts a new argument `--theme=none` which disables syntax highlighting. OK, let me ask a few questions:

- How are you installing delta? What's your `delta --version`? Are you downloading the executables from the releases page? Or if you're building from the git repo, can you pull master and confirm what commit you're on?

- It looks like you're on linux, can you confirm the OS and terminal app?

- How are you configuring delta? Can you show me the line in your .gitconfig? Since you are using a dark terminal background, I'd recommend using `--dark`. However, it looks like you've got `--light` there (right?)

- The widths of the background color look wrong in your screenshot. It could be a bug that I'm unaware of on your system, but I'm wondering -- did you happen to resize the terminal before taking the screenshot?

**Comment by iomintz** [comment]
1. `git pull` on master, followed by `cargo install`. `delta 0.0.10`
2. Arch Linux, xfce4-terminal 0.8.8
3. You're right, I forgot --dark. My old line was `pager = delta --theme none`. `pager = delta --theme none --dark` improved things. Now it looks like this:
![screenshot](https://user-images.githubusercontent.com/538336/66005043-eff7ad80-e46f-11e9-9660-7ea4d2a00959.png)
4. I did not resize the terminal first. Just in case, the screenshot I posted in (3) is of a brand new terminal window. If I make the window wider afterwards, the "extra blank lines" (which are really caused by the overlong background colors being wrapped) disappear. Here is the same view, at a width of 138 (shortest width that is wide enough to contain the background colors):
![image](https://user-images.githubusercontent.com/538336/66005366-d60a9a80-e470-11e9-844c-1f086c7cd12d.png)

**Comment by iomintz** [comment]
Just noticed that 0.0.10 is out of date. I'm on 2ba73e32d57075bb8b34181752f977fcbadfe5f5 (0.0.12) now, and I can still reproduce.

**Comment by dandavison** [comment]
Ah, are there tab characters in the python code? Delta currently cannot calculate the correct line width when there are tabs present because it doesn't know how much width the tab takes up when it is rendered.

**Comment by iomintz** [comment]
Yes, I use tabs for indentation. Should I find another tool?

**Comment by dandavison** [comment]
Hopefully your python code looks better on master now? By default, delta will render tabs 4 spaces wide, so it looks like you might need `--tabs=8`.

**Comment by runxiyu** [comment]
Appears to be syntax-theme now, for anyone reading this now
