### ISSUE TITLE
🚀 Add option to override terminal's background color

### ISSUE THREAD

**Issue by jc00ke** [dandavison/delta#153]
![image](https://user-images.githubusercontent.com/18191/80529671-a5c6a400-894c-11ea-8cc5-c880ce4b1bd2.png)

(`yadm` just forwards, and I tested it with bare `git` too)

Am I doing something silly? This is with `delta 0.1.1` on Linux with `kitty 0.17.3`

**Comment by jc00ke** [comment]
Hmm, even `delta --list-themes` looks off...
![image](https://user-images.githubusercontent.com/18191/80530080-592f9880-894d-11ea-94b4-21526fd17882.png)

**Comment by dandavison** [comment]
Hi @jc00ke, thanks for opening an issue! It may be that I've done something that doesn't make sense or is surprising people. Currently, delta only alters the background color in added/removed lines. Otherwise, the background color is whatever your terminal emulator is producing. Is is that that's violating your expectations?

**Comment by dandavison** [comment]
> the background color is whatever your terminal emulator is producing.

I believe that bat takes the same approach: https://github.com/sharkdp/bat/issues/339#issuecomment-441818719

Does this make sense? There have also been questions about it in #87. (Wouldn't it be rather visually jarring for delta/bat to produce different background colors from what your terminal is set to?)

**Comment by jc00ke** [comment]
Ah, that makes sense, and yes, that's violating my expectations :wink:
I had the expectation that the background would match the selected theme, that way the highlighted line and colors would adhere to the theme better. I didn't realize `bat` does that as well, and it makes sense, but it also makes sense to think of it like someone setting a piece of paper on my desk. The paper's color shouldn't match the color of my desk.

As for a jarring experience, yes, totally. I had `light` set to test the background, but I'll switch to `dark` since that's my default Solarized variant. For a while I ran `vimdiff` with the light variant just to really make it clear I was in diffing mode. But I don't personally mind :stuck_out_tongue_winking_eye:

**Comment by gpressutto5** [comment]
It would be great to have an option to change the background for not changed lines too. This way we could use light themes for diff while still using a dark theme for terminal.

**Comment by dandavison** [comment]
@jc00ke @gpressutto5 @natsumi @lightspeedbriefs

The `master` branch of delta now allows the background color to be set, overriding the terminal. Please see the write-up in #205 for full details!

Here's an example showing how to use a light theme with a dark terminal background, as @gpressutto5 suggested:

```
delta --theme=OneHalfLight --minus-style 'syntax auto' --minus-emph-style='syntax auto'
      --zero-style 'syntax white'
      --plus-style 'syntax auto' --plus-emph-style 'syntax auto'
      --hunk-header-style='syntax white' --hunk-header-decoration-style='black box'
```

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/83202633-fe3cbd00-a115-11ea-9c77-6552a7c4b69e.png" alt="image" /></td></tr></table>


### To build delta from source:

You'll need to [install the rust tools](https://www.rust-lang.org/learn/get-started).

```
git pull origin master
cargo build --release
./target/release/delta --help
```

Closing this because I think it's fixed, but as always please re-open if not.
