### ISSUE TITLE
🚀 Add foreground-color options

### ISSUE THREAD

**Issue by boris-petrov** [dandavison/delta#177]
I'm so used to `diff-so-fancy`'s output that I want the same with `delta`! :) That is, the whole "added" line to be black background (depending on the terminal's color of course), green foreground and green background/other-green foreground for the changed parts. The same for the "removed" lines - black background, red foreground and red background/other-red foreground for the changed parts.

I guess options for all of these are needed. :smile:

**Comment by bluz71** [comment]
I am also a long-time `diff-so-fancy` user and have gotten used to, and now like the style, of that utility.

However it is much slower than `delta`, which I only just came across the other day.

Providing the ability to set the foreground colours would sincerely be most welcome since we could replicate the `diff-so-fancy` look but now with with `delta` speed.

Many thanks for this fast utility.

**Comment by dandavison** [comment]
@boris-petrov @bluz71 @CSRaghunandan @mk12 diff-so-fancy / diff-highlight emulation is now available in `master` (not released yet). #204 contains a write-up of the new options.

Here's an example using the colors from the example in the diff-so-fancy README:

```
delta --minus-style 'red bold' --minus-emph-style 'red bold 52'
      --zero-style 'normal'
      --plus-style 'green bold' --plus-emph-style 'green bold 22'
      --hunk-header-style 'bold syntax' --hunk-header-decoration-style 'bold magenta box'
      --file-style 'bold yellow' --file-decoration-style 'bold yellow underoverline'
      --commit-style 'bold yellow'
```

<table>
    <tr>
        <td>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        delta
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        diff-so-fancy
        </td>
    </tr>
    <tr><td><img width=700px src="https://user-images.githubusercontent.com/52205/83186886-3aaeef80-a0fb-11ea-95ad-26e11dafe7ce.png" alt="image" /></td></tr>
    <tr>
        <td>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        delta
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        diff-so-fancy
        </td>
    </tr>
    <tr><td><img width=700px src="https://user-images.githubusercontent.com/52205/83186804-1521e600-a0fb-11ea-888a-1e586388de37.png" alt="image" /></td></tr>
</table>


Here's another example of doing something similar, from #193:

```
delta --minus-style=red --minus-emph-style='reverse red'
      --plus-style=green --plus-emph-style='reverse green'
```

### To build delta from source:

You'll need to [install the rust tools](https://www.rust-lang.org/learn/get-started).

```
git pull origin master
cargo build --release
./target/release/delta --help
```

I'm closing this because I think it's fixed but let me know and reopen if not!
