### ISSUE TITLE
🚀 Add your own custom themes

### ISSUE THREAD

**Issue by AlaaMansourTW** [dandavison/delta#180]
Hi! thanks for the amazing tool, I was wondering if there's a way to use our own theme?
I am aware that `delta` uses the bat themes but I don't want to add my theme to `bat`, I would like to use my custom theme locally. Is that possible?
Cheers!

**Comment by dandavison** [comment]
Hi @AlaaMansourTW, yes, this is possible! I've just edited the relevant section of the README to make it clearer. Here's what it says now:

------------------------

To add your own custom color theme, or language, please follow the instructions in the Customization section of the [bat documentation](https://github.com/sharkdp/bat/#customization):
- [Adding a custom language](https://github.com/sharkdp/bat/#adding-new-syntaxes--language-definitions)
- [Adding a custom theme](https://github.com/sharkdp/bat/#adding-new-themes)

Delta automatically recognizes custom themes and languages added to bat. You will need to install bat in order to run the `bat cache --build` command.
