### ISSUE TITLE
🚀 Minimal color mode reusing the default colors

### ISSUE THREAD

**Issue by waldyrious** [dandavison/delta#193]
I've been using git's [diff-highlight](https://github.com/git/git/tree/master/contrib/diff-highlight) script and I like the way it handles colors — it supports inline insertion/deletion highlighting (not as well as `delta`) using the reversed/negative style based on the same red/green colors used for the non-highlighted parts.

I would love if delta had an option to do the same. Right now, the difference is quite jarring to my eyes:

| `git` | `diff-highlight` |
|-|-|
| <img width="325" alt="diff" src="https://user-images.githubusercontent.com/478237/82128509-8ab0bc80-97b3-11ea-8524-dbf55a60f666.png"> | <img width="325" alt="diff-highlight" src="https://user-images.githubusercontent.com/478237/82128507-8a182600-97b3-11ea-840e-e08ec870d420.png"> |

| `delta --color-only` | `delta` |
|--|--|
<img width="325" alt="diff-delta--color-only" src="https://user-images.githubusercontent.com/478237/82128504-88e6f900-97b3-11ea-95b2-29271fc65b2a.png"> | <img width="325" alt="diff-delta" src="https://user-images.githubusercontent.com/478237/82128506-897f8f80-97b3-11ea-9efa-950c9ce86ad0.png"> |

For comparison, here's what `diff-so-fancy` does. Note how it reuses the original colors for added/deleted text, as well as for the file and hunk headers (although it does introduce a different shade of green for the inline highlight, which I've reported in https://github.com/so-fancy/diff-so-fancy/issues/374):

<img width="325" alt="diff-so-fancy" src="https://user-images.githubusercontent.com/478237/82128650-994ba380-97b4-11ea-8200-c4cec08f9c1f.png">

**Comment by waldyrious** [comment]
By the way, shouldn't the "yeah" part of the diff be highlighted by `delta`? Is that a bug?

**Comment by dandavison** [comment]
Hi  @waldyrious, this is awesome and very helpful, thanks very much. The good news is I'm working on this right now. (See also #177).

> By the way, shouldn't the "yeah" part of the diff be highlighted by delta? Is that a bug?

Does it highlight with a value like `--max-line-distance=0.7`? See #140 for discussion. If you were able to try out the experimental environment variable introduced in #140 or otherwise provide feedback on improving the defaults for within-line edit highlighting that would be fantastic too.

**Comment by waldyrious** [comment]
> The good news is I'm working on this right now. (See also #177).

Yay! That's great to hear. :tada:

> Does it highlight with a value like `--max-line-distance=0.7`?

It still doesn't. 😢 I tried with various values, but none worked to highlight just the "yeah" part of the line. In any case, that's a discussion to continue in #140 :) I'll follow that thread and chime in with any feedback I can provide.

**Comment by dandavison** [comment]
@waldyrious I believe this is now fixed in `master` (not released yet). Please see the write-up in #204 for full details!

```
delta --minus-style=red --minus-emph-style='reverse red'
      --plus-style=green --plus-emph-style='reverse green'
```

<table><tr><td><img width=700px src="https://user-images.githubusercontent.com/52205/83199205-c2eac000-a10e-11ea-8ab2-1f70d3e97819.png" alt="image" /></td></tr></table>

`reverse` is a style attribute that is now supported by delta, in addition to `bold`, `dimmed`, `ul`, etc. There are some alternative ways of doing the same thing here, e.g. instead of using `reverse` with a foreground color, one could give foreground and background colors like `--minus-emph-style='normal red'`.

Closing because I believe fixed but let me know if not!

Next up: what is going on with that `foo yeah` not highlighting! (I certainly see that you're right and it does not highlight even with `--max-line-distance 1.0`.)
