### ISSUE TITLE
🐛 Diff is confusing when the line is whitespace only

### ISSUE THREAD

**Issue by FranklinYu** [dandavison/delta#212]
Steps to reproduce:

1. Clone any repository, such as this one.
2. Edit a file with an empty line on it, such as `Cargo.toml`.
3. Add a space (or tab) to the empty line.
4. `git diff`

Git raw diff:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 7c7e71f..7330174 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -10,7 +10,7 @@ license = "MIT"
 readme = "README.md"
 repository = "https://github.com/dandavison/delta"
 version = "0.2.0"
-
+
 [[bin]]
 name = "delta"
 path = "src/main.rs"
@@ -36,6 +36,6 @@ default-features = false
 features = ["parsing", "assets", "yaml-load", "dump-load", "regex-onig"]

 [dependencies.error-chain]
-version = "0.12.2"
+version = "0.12.2"
 default-features = false
 features = []
```

Screenshot of Git raw diff:

![image](https://user-images.githubusercontent.com/3153452/83365449-00448d00-a35d-11ea-93cc-3207b2f918bb.png)

Screenshot of Delta diff:

![image](https://user-images.githubusercontent.com/3153452/83365477-2a964a80-a35d-11ea-916c-32984fa10a15.png)

Note that, as comparison, trailing whitespace is rendered correctly. I would like a whitespace-only line to look the same.

### Environments

 - Delta 0.1.1
 - macOS Catalina
 - Git 2.24.3 (macOS built-in version)

**Comment by dandavison** [comment]
Agreed, this needs addressing. Thanks @FranklinYu.

**Comment by dandavison** [comment]
Linking similar bug pointed out by @mk12 in  https://github.com/dandavison/delta/issues/205#issuecomment-638479178, which is related to this one. `diff-so-fancy` has [markEmptyLines](https://github.com/so-fancy/diff-so-fancy#markemptylines) which is relevant.

**Comment by dandavison** [comment]
Thanks again @FranklinYu, the issue with delta failing to highlight added whitespace on a blank line is fixed in master (it was a straight-out bug -- a divide-by-zero when calculating the distance between the two lines in terms of edit operations).

I still need to fix the problem of blank line additions/removals being invisible when there is no background color, perhaps by adding a space. https://github.com/dandavison/delta/issues/179#issuecomment-625875095 is relevant (discussion about whether delta can drop the space in the first column that it currently emits as a replacement for the `-`/`+` marker).

**Comment by dandavison** [comment]
Moving remaining discussion to #179
