### ISSUE TITLE
🐛Running some of the commands like (--theme) hangs forever.

### ISSUE THREAD

**Issue by rafamerlin** [dandavison/delta#213]
So, I've installed it on windows 10 manually by downloading the release and adding to a folder where my PATH is.

It's working fine in Mintty and also in Cmder (using Mintty inside), however, the colours on Cmder are quite off, I try to select a theme but it just doesn't work. 

If I run 
`delta` it hangs forever
if I run `delta -V` it works fine, I can also list all the themes but I can't select a different theme.

Tried both of these:
`delta --theme Dracula` 
and 
`delta --theme=none`

And the command never finishes running and nothing gets outputted, I've waited around 30 mins and nothing happened so I just Ctrl+C it and stopped the process.

Is there a verbose command I can run or something of the sorts to get any type of logs?

**Comment by dandavison** [comment]
Hi @rafamerlin, you're right -- it will hang forever if we just run `delta` or `delta --theme xxx`. This is because `delta` requires that it is given its input (i.e. some sort of diff) on "standard input". There are a few common ways to do that:

1. Configure git to send its output to delta automatically. This is the most common way of using delta. It's covered in the [README](https://github.com/dandavison/delta#configure-git-to-use-delta).

2. Send output from git to delta manually. For this you can do something like `git diff | delta` or `git diff | delta --theme Dracula`. That `|` syntax is a pipe, sending the output from `git` into the "standard input" of delta.

3. Similar to 2, but not using `git`, you can feed delta a diff between two files by doing `diff -u file_A file_B | delta`

In all these commands, you can put any of delta's options after the word `delta`.

**Comment by rafamerlin** [comment]
Fantastic. Thanks for answering so quickly :)

**Comment by dandavison** [comment]
No problem! It is possible to get delta's colors to appear correctly on Windows, but there is an extra step you might have to take.  It's documented [here](https://github.com/dandavison/delta#windows) -- basically the recommendation is to use a newer version of the `less` program which fixes some bugs which affect `delta`.
