### ISSUE TITLE
🐛 Incorrect syntax highlighting in .vim file

### ISSUE THREAD

**Issue by FranklinYu** [dandavison/delta#222]
Example:

```vim
set runtimepath=~/foo/bar
```

`/foo/` would be highlighted. I think it was recognized as Regular Expression.

**Comment by dandavison** [comment]
Hi @FranklinYu! Can you post the raw diff that is causing the bug (and maybe a screenshot showing what you see)?

**Comment by FranklinYu** [comment]
Screenshot:

![image](https://user-images.githubusercontent.com/3153452/85096951-c07a0400-b1aa-11ea-9ea1-9a3e2bf5b7a2.png)

I don’t think the raw diff is required to verify the bug? It’s just the syntax highlighter issue.

**Comment by dandavison** [comment]
Ah, I see. OK, so Delta does not maintain language syntax definitions. Delta shares the same syntax definition files as [bat](https://github.com/sharkdp/bat/) and the behavior you're seeing is present in bat also (see below).

The question is -- where to report this bug (I don't know much about vim but I agree it looks like a bug.)

After poking around a bit, I think that the relevant file in bat is `assets/syntaxes/02_Extra/VimL.sublime-syntax` and that this repo might be the place to report it: https://github.com/evandroforks/VimL

Then, once it is fixed in that upstream, you could open an issue in bat asking them to update their vim syntax.

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/85144036-9828ee80-b218-11ea-9771-0c0fcab382b8.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
@sharkdp / @eth-p would you mind advising here? The question is: what should a bat (or delta) user do if they discover a syntax-highlighting bug affecting, say, a `.vim` file? I don't _think_ it's bat's responsibility, and after poking around a bit I'm thinking that the relevant repo might be https://github.com/evandroforks/VimL. However, I wonder if it could be made a bit more clear in the bat README what the procedure to follow is in general? I can open a bat issue asking for that, if that is the way forwards.

More details: here's what I did to try to answer this specific question about vim syntax:

- I looked in `bat/assets` and saw the `VimL` submodule and the `VimL.sublime-syntax` file.
- I guessed that the relevant file is `assets/syntaxes/02_Extra/VimL.sublime-syntax` and not `assets/syntaxes/02_Extra/VimL/VimL.tmLanguage` (do both need to exist in bat?)
- I used `git log` in the bat repo to try to discover the provenance of `VimL.sublime-syntax`, but didn't succeed.
- I did a google search and came across https://github.com/evandroforks/VimL. That repo contains `VimL.sublime-syntax` and is somehow related to the submodule in bat (which does not contain that file), but I don't understand the relationship.

**Comment by FranklinYu** [comment]
We can have a GitHub issue tag `upstream` so we keep track of the issues without spending too much time in it. Maybe I also report to bat and link the issue there?

**Comment by FranklinYu** [comment]
sharkdp/bat#1064

**Comment by dandavison** [comment]
Great, let's allow https://github.com/sharkdp/bat/issues/1064 to be the live issue here for now, at least to establish whether bat is the correct repo or whether these go upstream to a syntax repo.

**Comment by sharkdp** [comment]
>  The question is: what should a bat (or delta) user do if they discover a syntax-highlighting bug affecting, say, a `.vim` file?

In an ideal world: find the upstream repository, get the fix merged there, then wait for the fix to be automatically merged into `bat` with the next (semi-automated) submodule update.

> I don't _think_ it's bat's responsibility, and after poking around a bit I'm thinking that the relevant repo might be https://github.com/evandroforks/VimL.

Yes - we keep all syntaxes as submodules in https://github.com/sharkdp/bat/tree/master/assets/syntaxes/02_Extra
For most syntaxes, adding the submodule is enough. For some of them, we need to manually convert from `.tmLanguage` to `.sublime-syntax`. In this case, there will be an additional file in that folder.

> However, I wonder if it could be made a bit more clear in the bat README what the procedure to follow is in general?

Yes, absolutely. We have an additional README here: https://github.com/sharkdp/bat/tree/master/assets - but it could certainly be linked in the main README and documentation can always be improved.

> I used `git log` in the bat repo to try to discover the provenance of `VimL.sublime-syntax`, but didn't succeed.

Probably because it was added via manual conversion (see above).

> I did a google search and came across https://github.com/evandroforks/VimL. That repo contains a very similar version of `VimL.sublime-syntax` and is somehow related to the submodule in bat (which does not contain that file), but I don't understand the relationship.

We actually use https://github.com/SalGnt/Sublime-VimL/tree/ed40c3bc814cd0c8107dbbb8fcd95946b33217f0 (see submodule link)
