### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by JNRowe** [dandavison/delta#223]
Hi,

  First up, **great tool**!

 ---

  I was just about to open a new issue, but luckily spotted [my problem](https://github.com/dandavison/delta/issues/215) has already been fixed(_thank you_!).  It did make me wonder if I was using a massively old release, and [perhaps I am](https://github.com/dandavison/delta/compare/0.1.1...master).  Right now there are 277 changes since the [last release](https://github.com/dandavison/delta/releases/), a good chunk of which look to be big functional improvements and fixes.

  Perhaps the intention is for people to just build directly from `master`, but maybe it is time for a new tagged release?

Thanks,

James

PS. I hope this doesn't come across as pushy and entitled, and I do understand that cutting a new release can be a nervous chunk of work ;)

**Comment by dandavison** [comment]
Hi @JNRowe, definitely agree! Let's leave this issue open until it's done. I'm hoping for next week. This one has taken too long  -- a large number of bug fixes and refactoring got bundled up with new features (arbitrary foreground/background styling with glyph attributes for all stylable elements, ~/.gitconfig for configuration, line numbering, diff-highlight and diff-so-0fancy emulation, mix-and-matchable named collections of options ("presets")) and it's taken a while to straighten out. It is now basically stable, just whitespace handling that I'm aiming to fix before release (#179). Plus new documentation. I've learned my lesson though and aim to do better branch management, e.g. hotfixes on a releasable branch, in the future. 

If you are able to build master, then using that and letting me know of any problems would be fantastic.

**Comment by dandavison** [comment]
Thanks @JNRowe, 0.2.0 is released now.

------------------------

From the release notes (https://github.com/dandavison/delta/releases/tag/0.2.0):

The highlights are:

- To configure delta's appearance, you now use "styles" instead of background color names. A style is a string like `red bold ul "#ffeeee"` that specifies foreground color, background color, and attributes. See https://github.com/dandavison/delta#choosing-colors-styles.

- Delta now reads configuration from a `[delta]` section in git config, and this is the recommended way to configure delta. See https://github.com/dandavison/delta#configuration

- Delta now has a line numbers feature, thanks to @clnoll. See https://github.com/dandavison/delta/pull/190, https://github.com/dandavison/delta/pull/219

- Delta now has `--diff-highlight` and `--diff-so-fancy` emulation modes (thanks @waldyrious for much testing)
