### ISSUE TITLE
🐛--show-background-colors is printing bogus colors

### ISSUE THREAD

**Issue by lilyball** [dandavison/delta#226]
When I run `delta --show-background-colors` it's printing obviously bogus colors. For example, it claims that the default dark green plus color is `#160000`. This is making it very hard for me to tweak the color because I can't tell what the default is.

This was reproduced with delta 0.1.1 running in Terminal.app.

<img width="907" alt="Screen Shot 2020-06-18 at 10 21 12 PM" src="https://user-images.githubusercontent.com/714/85099370-11d9c180-b1b2-11ea-810f-e655c1f88c43.png">

**Comment by dandavison** [comment]
Hi @lilyball, thanks for this. I can reproduce it -- when I use `--24-bit-color=never`. I'll look into the bug and fix it.

I believe that you're seeing the same as `--24-bit-color=never` because `Terminal.app` doesn't support 24-bit colors. This does make delta a bit less fun. Depending on how attached you are to Terminal.app, you could give iTerm2 a go (or another MacOS terminal emulator). You probably saw 24-bit-color notes [here](https://github.com/dandavison/delta#24-bit-color-truecolor) in the README.

![image](https://user-images.githubusercontent.com/52205/85181037-fc68a400-b252-11ea-9777-a7c355303201.png)

**Comment by dandavison** [comment]
This is fixed in master, to be released soon. The command has been renamed `--show-config`

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/85931966-1da24380-b896-11ea-8c35-6288cf8e8920.png" alt="image" /></td></tr></table>

**Comment by dandavison** [comment]
v0.2.0 was released today which includes the new `--show-config` flag.
