### ISSUE TITLE
🐛  Mismatch in line numbers between git diff and git add -p

### ISSUE THREAD

**Issue by davidmatas** [dandavison/delta#258]
Hi,

I'm getting differences in lines number between `git diff` and `git add -p` execution. See the following captures:

`git add -p`
![image](https://user-images.githubusercontent.com/271760/87882015-69f82380-c9fd-11ea-9602-500aec51437e.png)

`git diff`
![image](https://user-images.githubusercontent.com/271760/87882024-7da38a00-c9fd-11ea-8d0e-7cbdc4a8f724.png)

The correct one is the one I'm getting in `git diff`.

Versions:

delta: `0.3.0`
git: `2.27.0`

**Comment by yoichi** [comment]
The problem occurs when we have following setting in gitconfig:

```
[interactive]
	diffFilter = delta --color-only
[delta]
	line-numbers = true
```

More precisely, it is caused since handle_header_line is skipped at
https://github.com/dandavison/delta/blob/master/src/delta.rs#L116

On the other hand, if we call handle_header_line there even when raw/color-only option is set by changing code as follows,
then `git add -p` cause error.

![スクリーンショット 2020-07-22 5 31 40](https://user-images.githubusercontent.com/107537/88103954-b3eb3000-cbdc-11ea-8945-80bff90193da.png)

The error is caused since an empty line is added in its output for a hunk.

**Comment by dandavison** [comment]
Hi @davidmatas, @yoichi, thanks very much for opening this, and for the investigation & analysis, and now a PR! (I'm sorry, I thought I'd commented already to acknowledge this helpful issue submission, but apparently my comment didn't get submitted and I didn't realize.)
