### ISSUE TITLE
🚀Compatibility with 'most'

### ISSUE THREAD

**Issue by DanielRivasMD** [dandavison/delta#268]
Hi. Great tool, love it! However, I began using 'most' as default PAGER, which happens to be incompatible with 'delta'. All colors are interpreted as string literals. Any hope this could be fixed? Much appreciated.

**Comment by dandavison** [comment]
Hi @DanielRivasMD, thanks! Which of the following are you asking?

1. You want to have `PAGER=most` and use `most` for your general shell usage, but you're happy for Delta to continue to use `less`.

2. You want Delta to be able to use `most`.

If you're asking (2), then I think the answer's probably no -- Delta is only going to undertake to work with `less` for now. I'm curious though -- does `git` work with `most` or do the colors not work there also?

However, you're probably asking (1). If so, then the answer is:

Currently, it's perhaps a bit odd, but Delta respects `BAT_PAGER`, so you can set that to use `less -R`, e.g.

```sh
export BAT_PAGER='less -R'
```

or any other `less` options you want, as long as you keep `-R`.

Delta gives precedence to `BAT_PAGER` over `PAGER`, so you should be able to keep `PAGER` set to `most`.

In the future I do one or both of the following:

1. Support an environment variable DELTA_PAGER
1. Add a `--pager` argument like `bat` has.

But I haven't done either of those yet. I'll post to this ticket if I do!

**Comment by dandavison** [comment]
OK, I did a quick experiment. It looks to me like `most` only has very limited color support: specifically it looks to me like it only supports the 8 basic terminal colors, but supports neither 256-colors nor 24-bit colors:

This works, because by default Git only uses the 8 basic terminal colors:

```
HOME=/dev/null git -c 'core.pager=most' log -p
``` 

But this does not, because it requests git to output a 256-color ANSI color code:

```
HOME=/dev/null git -c 'core.pager=most' -c 'color.diff.old=88' log -p
```

You can see a literal `^[[38;5;88m` in the output, which is an ANSI 256-color code.

So if I'm right about that, then the answer to (1) is: yes, technically one can use Delta with most, but only if you stick to the 8 basic terminal colors. However, that's extremely limiting, and I think means that you won't be able to use syntax-highlighting, because the sublime themes used by delta (and bat) make use of more colors...except for themes like [base16](https://github.com/chriskempson/base16). But, I don't _think_ most even supports 16 colors:

```
HOME=/dev/null git -c 'core.pager=most' -c 'color.diff.old=9' log -p 
```

That should have produced a "brightred" color, but again we see most emitting the ANSI sequence literally (`^[[90m`).

**Comment by DanielRivasMD** [comment]
Thanks. This is quite helpful. I will use your suggestions.

**Comment by dandavison** [comment]
Great. I'll close this for now but feel absolutely free to keep the discussion going or re-open.
