### ISSUE TITLE
🐛 Dockerfile isn't colored

### ISSUE THREAD

**Issue by kjmph** [dandavison/delta#275]
Here is an example Dockerfile:

```
$ cat Dockerfile
FROM debian
RUN echo "Hello World"

CMD ["/bin/bash"]
$ git diff | cat
diff --git a/Dockerfile b/Dockerfile
index 909c906..d43d53c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,2 +1,4 @@
 FROM debian
 RUN echo "Hello World"
+
+CMD ["/bin/bash"]
```

However, here is a screenshot of the delta output:

<img width="346" alt="Screen Shot 2020-08-05 at 9 43 44 PM" src="https://user-images.githubusercontent.com/1075649/89488423-37705980-d765-11ea-9d6d-4d6a8e6b10da.png">

`bat` does have support for Dockerfile coloring:

<img width="273" alt="Screen Shot 2020-08-05 at 9 48 09 PM" src="https://user-images.githubusercontent.com/1075649/89488471-5ec72680-d765-11ea-82ac-e358398ea303.png">

Any other information I can provide? Other files are colored fine. Except that I notice a Makefile seems to lose colors after the hunk, maybe it is related to files without extensions?

<img width="753" alt="Screen Shot 2020-08-05 at 9 49 51 PM" src="https://user-images.githubusercontent.com/1075649/89488611-b4033800-d765-11ea-9fdc-29b1318addb8.png">

**Comment by dandavison** [comment]
I'm glad you opened this @kjmph. The bug has been around for ages, and I had seen it myself. I think somehow recently I'd started to believe that since Makefiles were working, things like Dockerfile were also. In any case, I've almost fixed this, and the cause of the bug revealed something which is good to fix -- that delta was sending code to the syntax-highlighting library prefixed with a space, for unrelated reasons. I think the Dockerfile sublime syntax definition has some regular expressions that require keywords anchored at the beginning, but the space would surely have ended up causing other problems.

**Comment by dandavison** [comment]
The merged PR fixes the Makefile problem you reported also. I am not entirely sure but my guess is that the lack of conventional file extensions was a red herring and the issue was anchored regexes in the syntax definition files.

Thanks for reporting these bugs!

**Comment by kjmph** [comment]
Lovely, thank you so much for the quick turn around. Makefiles and Dockerfiles are nice and colored now! Delta is a great project, thanks for the work.
