### ISSUE TITLE
All the dark themes use the same colors

### ISSUE THREAD

**Issue by deanhouseholder** [dandavison/delta#31]
For some reason in multiple terminals (Hyper.js and iTerm2) on Mac OS X 10.14.6, all the dark themes look exactly the same.

![All Delta dark themes all look the same](https://uc3adfadc23332ffb0072ef20891.previews.dropboxusercontent.com/p/thumb/AAm3P1ktJrN6Bsxp6emthFwIN3JDN2iQQGwjbj5QLGIi8cjPnZ7ZmIws08M--Bcrzq4xGJBzusT4ShYQfiZ4T9QtS1Bvve6_BLynyhag1RTTtv4n0jWut7PLV4mj0FNDp64TKyCbcBzjKgfhqg1y7H2KzZrT7wMieRAhmhV-C-ZZNzAqtTiInSQ3gAYx5RExSaKVxgxPe3TyRDFjosl_zgbMi6z5YanzKfgRl0g9o1g1r5ksdL-GnMzntsQETC9JnMfnT_0TCwjcnAFfJif3ky84sbHX9rYwXj-9Bbz43GXWSEaF24NsL1kGP04_I_5LK2tBYJYQRvD_wF5DZvm8T08CxxjtEvByvLwz3yO0Ps40fZx5KFMXENqbj5rmIoM_4jY-WkFZuag0Dwrm6O4WKDueo747vBUcyPhCvm36hUituG0iBp7hZK926ydwkIy1Ls92dSKQ1nJ9ni7SlKhprJgc4wwPBXKMrZmZmPDlqC0zW9G8_4CRxKgLra-yGHWp4Gw/p.png?fv_content=true&size_mode=5)

**Comment by dandavison** [comment]
This is actually correct behavior: `--show-colors` is showing the _background_ colors that delta uses to highlight added and removed content (plus and minus lines, and emphasized within-line sections). In contrast, the "theme" determines the _foreground_ colors that are used for language syntax highlighting (by [syntect](https://github.com/trishume/syntect)). So in your examples, you're not changing the background colors. (You could change them with something like `delta --show-colors --minus-color="#C3A3F3"`)

You raise a good point: I think maybe I should rename that option `--show-background-colors` or something, instead of simply `--show-colors`.

To look at the differences between _themes_, you can use `delta --compare-themes` (you can pipe your own git output into that command, or if you don't it will use some default diff output.)

**Comment by dandavison** [comment]
I've changed the option name and improved the help text (see #32). Thanks for prompting.

**Comment by deanhouseholder** [comment]
Cool. 🙂
