### ISSUE TITLE
🐛 Strange choices in word diff highlighting

### ISSUE THREAD

**Issue by torarnv** [dandavison/delta#342]
Delta:
![image](https://user-images.githubusercontent.com/7536/95000089-1473f180-05be-11eb-8c21-a777fbc7aebd.png)
![image](https://user-images.githubusercontent.com/7536/95000094-1b9aff80-05be-11eb-953c-faece9baeec3.png)

diff-so-fancy:
![image](https://user-images.githubusercontent.com/7536/95000101-26ee2b00-05be-11eb-9fed-7c00baa959c3.png)
![image](https://user-images.githubusercontent.com/7536/95000104-2bb2df00-05be-11eb-94d9-5dc4bd36b4a3.png)

Is there any way to get  the latter output for delta? Or to tweak delta to not be so aggressive in trying to find word differences?

**Comment by dandavison** [comment]
Hi @torarnv, thanks for opening an issue. The main tweak for delta's word-highlighting that is exposed currently is `max-line-distance`. Have you tried experimenting with that? Beyond that, the main discussion of development in this area is https://github.com/dandavison/delta/issues/140. I would love to hear suggestions for how the algorithms should be improved.

One thing that has not been done is implement diff-highlight's deliberately simple-minded algorithm (documented [here](https://github.com/git/git/tree/master/contrib/diff-highlight)). This is what diff-so-fancy uses, since diff-do-fancy is built on top of diff-highlight.

> Is there any way to get the latter output for delta?

What would you say is the definition of the behavior you want there? It appears that diff-so-fancy has not added any word highlighting at all in those cases. That can of course be achieved in delta! Two ways come to mind: the most natural is setting `max-line-distance` to 0.0. In theory you could also tweak the "emph" style colors to be the same as non-emph.

**Comment by torarnv** [comment]
Turns out setting `max-line-distance = 0.3` was all that was needed indeed 😊 Sorry for the noise!

I'm not sure what a good default would be. I'll read up on the issues you linked to and see if I can contribute, thanks!
