### ISSUE TITLE
Troubleshooting: Delta’s `less` instance acts as if it was passed `--quit-if-one-screen` (`-F`)

### ISSUE THREAD

**Issue by roryokane** [dandavison/delta#355]
## Problem

After setting Delta as the pager in my Git config and running `git diff`, the diff is colored with `delta`, which passes the colored dif to `less`, as expected. However, this instance of `less` acts differently from the instance of `less` I got when running `git diff` before.

If I press <kbd>q</kbd> in Delta’s instance of `less`, the diff I was viewing stays on screen and only my newest shell prompt is displayed. I preferred the behavior I had before, where Git’s `less` ran on the terminal’s “alternate screen”, and after exiting that instance of `less`, the screenful of diff I was viewing was no longer visible, allowing me to see my previous prompt (where I typed `git diff`) right above my new prompt.

I confirmed that my `LESS` environment variable doesn’t include `--quit-if-one-screen` or `-F`, which is why it surprises me that Delta’s instance of `less` is acting like that flag was passed.

```
$ echo $PAGER
less
$ echo $LESS
--ignore-case --LONG-PROMPT --window=-2 --RAW-CONTROL-CHARS
```

I already solved this issue for myself, as you can see below, but I’m posting an issue about it so other users who search Delta’s issue tracker can solve the issue faster. I didn’t see any Troubleshooting section in Delta’s README, which, if it existed, would be a better place for this.

## Solution

Upgrading `less` fixed this for me. On macOS 10.14, my built-in version of `less` was 487. Running `brew install less` (using [Homebrew](https://brew.sh/)) upgraded my `less` to version 551, fixing my problem.

I suspect the specific `less` change that solved the problem might be the change in `less` version 530 that is described in [this code comment within Delta](https://github.com/dandavison/delta/blob/9cf186c49b3969c21a1cab432bafdc87cf566292/src/bat/output.rs#L99-L105). As noted by that code comment, `--quit-if-one-screen` now works properly without having to specify `--no-init` too, obviating my original reason for removing `--quit-if-one-screen` from my `LESS` environment variable.

**Comment by dandavison** [comment]
Thanks very much for that @roryokane, I'll get it into the README shortly.

**Comment by eggbean** [comment]
Strange. I have the opposite problem where `LESS -F` is being ignored.  https://github.com/dandavison/delta/issues/1605

**Comment by marstj** [comment]
I ran into the same problem, but with a recent version of `less`. After spending some time debugging and digging into source code, it turns out that it's the `delta.paging` option that by default (value `auto`) passes `--quit-if-one-screen` if it thinks the pager is `less`.

So this should do the trick if you don't want quit-if-one-screen behaviour:

```
[delta]
	paging = always
```

I'm posting this here just for visibility since the bug title matches the behaviour.

(Imo this setting isn't ideal, because it activates a nontrivial context-dependent behind-the-scenes special case that is confusing, and it also does it by default, affecting users that aren't aware of the setting. I think it'd be better to not try to be clever and just let users configure their pager using the standard methods that git and the pager itself provides. But other than that, thanks for a nice tool.)
