### ISSUE TITLE
🐛 Delta spawns too many threads, causing thrasing

### ISSUE THREAD

**Issue by jyn514** [dandavison/delta#378]
```
$ git diff HEAD~ --stat
 Cargo.lock                                            |  15 +++++++++++++-
 library/alloc/tests/slice.rs                          | 120 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 library/backtrace                                     |   2 +-
 src/bootstrap/tool.rs                                 |   1 +
 src/doc/book                                          |   2 +-
 src/doc/edition-guide                                 |   2 +-
 src/doc/nomicon                                       |   2 +-
 src/doc/reference                                     |   2 +-
 src/doc/rust-by-example                               |   2 +-
 src/librustdoc/passes/collect_intra_doc_links.rs      |   3 +--
 src/llvm-project                                      |   2 +-
 src/test/ui/array-slice-vec/subslice-patterns-pass.rs | 126 ---------------------------------------------------------------------------------------------------------------
 src/tools/cargo                                       |   2 +-
 src/tools/miri                                        |   2 +-
 14 files changed, 145 insertions(+), 138 deletions(-)
$ PAGER= time -v git diff HEAD~ >/dev/null
	Command being timed: "git diff HEAD~"
	User time (seconds): 0.09
	System time (seconds): 0.18
	Percent of CPU this job got: 234%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.11
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 33516
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 9333
	Voluntary context switches: 131
	Involuntary context switches: 22
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
$ PAGER=delta time -v git diff HEAD~
... still running as I write this issue ...
```

This is https://github.com/rust-lang/rust/commit/1bdee96c5e6de445f09df34447a42553294f21ed. ltrace shows that there are hundreds of delta processes running:

```
$ ps -ef | grep delta | wc -l
996
```

**Comment by jyn514** [comment]
A secondary bug - `killall delta` only sometimes works, I need `killall -9` to be sure they actually exit.

**Comment by dandavison** [comment]
Hi @jyn514, I don't think I can reproduce this. (I used `HEAD~20` below to pick up a large diff; 1bdee96c5 only touches two files.) The delta code itself does not currently spawn any additional threads. My understanding was certainly that the calls to 3rd-party libraries and stdlib functions that delta makes also do not spawn additional threads. Sorry if I'm missing something here or misunderstanding! There haven't been any other reports of performance problems like this.

This is on MacOS.

```
rust(delta-378) git rev-parse HEAD
1bdee96c5e6de445f09df34447a42553294f21ed
rust(delta-378) PAGER= /usr/bin/time -l git diff HEAD~20 > /dev/null 
        0.23 real         0.18 user         0.15 sys
  58441728  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     18242  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         0  voluntary context switches
       152  involuntary context switches
rust(delta-378) PAGER= /usr/bin/time -l git diff HEAD~20 | delta > /dev/null
        0.55 real         0.18 user         0.14 sys
  57950208  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     18125  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
        46  voluntary context switches
       112  involuntary context switches
```

**Comment by dandavison** [comment]
Just in case I made a mistake with the way I used pipes with `time` there, here's the same thing but in a bash child process:

```
rust(delta-378) git rev-parse HEAD                                                    
1bdee96c5e6de445f09df34447a42553294f21ed
rust(delta-378) /usr/bin/time -l bash -c 'PAGER= git diff HEAD~20 > /dev/null' 
        0.23 real         0.18 user         0.15 sys
  58560512  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     18915  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
         1  voluntary context switches
        99  involuntary context switches
rust(delta-378) /usr/bin/time -l bash -c 'PAGER= git diff HEAD~20 | delta > /dev/null'
        0.60 real         0.63 user         0.18 sys
  58327040  maximum resident set size
         0  average shared memory size
         0  average unshared data size
         0  average unshared stack size
     25530  page reclaims
         0  page faults
         0  swaps
         0  block input operations
         0  block output operations
         0  messages sent
         0  messages received
         0  signals received
      4916  voluntary context switches
       218  involuntary context switches
```

**Comment by jyn514** [comment]
@dandavison you're running `PAGER= git diff`. I ran `PAGER=delta git diff`. Is that not how delta is meant to be used?

**Comment by dandavison** [comment]
Yes, your way of doing the experiment corresponds to the principal way in which delta is designed to be used.

I ran the experiment slightly differently so that I could send the output to /dev/null. (There's a risk of doing the experiment wrongly: if git detects that output is redirected or going to a pipe, then it will not invoke `core.pager` at all. I expect you already know that; I saw that you did not redirect to /dev/null in your delta timing experiment).

If there's a bug in delta, then it should surface regardless of whether delta is invoked behind-the-scenes by git or explicitly by the user via a pipe. Unless you can think of a reason that wouldn't be true?

I don't have a theory yet to explain your results. I've never seen hundreds of delta processes. If git were somehow going crazy spawning pager processes that would do it, but I'm not aware of a situation where that would happen.

Do you still see the slow times and many processes when you pipe to delta, or only when it is git spawning the delta process?

**Comment by dandavison** [comment]
The way I ran the experiment also prevents delta from spawning a child `less` process as its own pager, for the same reason as git: delta detects whether stdout is a tty, and only spawns a less process if it is.

**Comment by jyn514** [comment]
> I've never seen hundreds of delta processes. If git were somehow going crazy spawning pager processes that would do it
> delta detects whether stdout is a tty, and only spawns a less process if it is.

That was it! Here's a minimal repro:

```
$ echo >a.txt >b.txt
$ PAGER=delta delta a.txt b.txt # hangs forever
```

**Comment by Kr1ss-XD** [comment]
That looks loke a recursion to me. Maybe delta uses `$PAGER` instead of directly calling `less`.

**Comment by dandavison** [comment]
Haha! Beautiful. The delta fork bomb. I was having trouble reproing that for a moment, but eventually realized that I had to unset `BAT_PAGER` and `DELTA_PAGER` in order for it to become recursive ([relevant code](https://github.com/dandavison/delta/blob/de050ba4a41e651aae1d776a57570dd3e5adec40/src/bat/output.rs#L53-L56)).

Do either of you think a fix is needed? I'm kind of inclined to think that it's in the spirit of Unix to allow people to do stuff like that, and that code in delta saying "Hey, judging by the executable name it looks like you're about to create a cycle in your process call graph; I'm not going to allow that." would be no fun (and not truly correct since who knows how a user has named their executables.)

**Comment by Kr1ss-XD** [comment]
@jyn514 could you pls try to set `DELTA_PAGER=less` ?

Since that should have priority over `$PAGER`.

**Comment by Kr1ss-XD** [comment]
FWIW, I agree with you @dandavison that this is kind of expected behavior. Maybe we should add a warning to `README.md`.

**Comment by jyn514** [comment]
Yes, `DELTA_PAGER=less` fixes it.

I guess the reason I consider this a bug is that I don't expect a pager to be spawning other pagers. bat spawns pager, but it doesn't have this problem because it's not itself used as a pager. Delta suggests using it as the default pager for git, so I would expect that use case to be supported via environment variables.

**Comment by dandavison** [comment]
> bat spawns a pager, but it doesn't have this problem because it's not itself used as a pager. 

Actually, it looks like bat does contain the bail-out code. See https://github.com/sharkdp/bat/issues/1334#issuecomment-715911033. I think using bat as a pager makes sense -- bat can be described as an improved `less`. But I guess to do that one sets `PAGER=bat` and `BAT_PAGER=less` or the equivalent.

**Comment by Kr1ss-XD** [comment]
>  Delta suggests using it as the default pager for git

This should be configured via `git --config core.pager` or `$GIT_PAGER` though. (not `$PAGER`)

**Comment by dandavison** [comment]
> This should be configured via `git --config core.pager` or `$GIT_PAGER` though. (not `$PAGER`)

Yes, I think I agree that this is technically the correct answer. Unlike bat, no-one will be using delta as a general purpose pager, so I'm thinking the recursion is really only a danger in the precise situation of this ticket -- using environment variables to modify git's pager. Using `PAGER` rather than `GIT_PAGER` is certainly a natural thing to do when doing an experiment like that, but I think this problem is going to be sufficiently uncommon that the code doesn't need to actually watch for it and override the pager executable like general-purpose pager-spawning pagers like bat do. Perhaps this is my tendency to err on the side of purism over pragmatism :) Anyway, this is all pretty minor. Thanks @jyn514 for the issues you opened; if people hit this recursion again I'll stick in the protection.

**Comment by dandavison** [comment]
> if people hit this recursion again I'll stick in the protection.

Hit again in #529; recursion protection added in #531.
