### ISSUE TITLE
ctrl+c out of compare-themes not handled gracefully

### ISSUE THREAD

**Issue by lzybkr** [dandavison/delta#38]
I see this on both Windows and Linux. Sorry if this report is a big vague.

If I try --compare-themes and hit <kbd>ctrl+c</kbd>, sometimes it seems like `delta` tries to show another theme, or maybe just a couple lines, it's hard to tell what exactly is happening.

Once I saw this panic (on Windows):

```
Error: Os { code: 232, kind: BrokenPipe, message: "The pipe is being closed." }
```

but I haven't reproduced that. I do see some zombie `less` processes that I can't kill - again on Windows.

**Comment by dandavison** [comment]
Thanks, I can reproduce this on MacOS with `git show HEAD~20... | delta --compare-themes`, which causes it to pause due to less's paging, and then issuing <kbd>q</kbd>:

```
Error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
```

(It looks pretty clear from the code that delta's not doing the error handling in that code path that it does for the main path.)
