### ISSUE TITLE
🐛 Can't find libgit2 when installing from arch package

### ISSUE THREAD

**Issue by jspspike** [dandavison/delta#381]
Not sure if this is an issue that should be put here but after installing delta with the aur package on arch I get this error.

`delta: error while loading shared libraries: libgit2.so.1.0: cannot open shared object file: No such file or directory`.

The dependency that the package installs for libgit2 is `libgit2.so.1.1` so I had to create a symlink to `libgit2.so.1.0` in order to get it to work.

**Comment by dandavison** [comment]
Hi @jspspike , thanks for this. It looks the same as https://github.com/dandavison/delta/issues/373 I think. cc @Kr1ss-XD

**Comment by Kr1ss-XD** [comment]
@jspspike I'd suggest to remove the symlink, since untracked files especially in `/usr/lib/` have the potential to cause conflicts with the package management later on.

You should be able to run `delta` as normal after rebuilding the package against the updated `libgit2`. Also, it might be good to clear your cargo cache before. See also the [comment section](https://aur.archlinux.org/packages/git-delta) on the AUR website.

**Comment by jspspike** [comment]
Removing the symlink and reinstalling with a clean build also fixed the issue

**Comment by Kr1ss-XD** [comment]
Cool, thx for the heads-up !
