### ISSUE TITLE
🐛 PAGER= does nothing

### ISSUE THREAD

**Issue by jyn514** [dandavison/delta#386]
When I set `GIT_PAGER=`, git correctly does not send output through delta. However, if I set `PAGER=`, delta still sends output to a pager.

My use case is that I want to get the highlighting, etc. from delta, but without launching a pager: `PAGER= GIT_PAGER=delta git diff` (https://github.com/rust-lang/rust/pull/78752).

**Comment by dandavison** [comment]
Hi @jyn514, quick answer: you can use `--paging=never` for this.

Thanks though, I didn't realize before, but I see you're right that delta's behavior isn't quite the same as git's (and bat's): as you point out, they make a distinction between the env vars being not set at all (still page by default, since less sophisticated users may well not have the env var set and will expect paging) versus set to empty string (no paging).

**Comment by jyn514** [comment]
>  quick answer: you can use --paging=never for this.

Thanks - yeah, that works for delta, but I don't think it works across commands (https://github.com/rust-lang/rust/pull/78752#issuecomment-723652496). This would be nice to have so I can switch out delta with other programs and not have to know which I'm using.

**Comment by dandavison** [comment]
Yes, makes sense. Thanks for this, fixed in master.
