### ISSUE TITLE
🚀 About etc/assets/syntaxes.bin and supporting all base16 themes at once

### ISSUE THREAD

**Issue by tgy** [dandavison/delta#387]
First of all, thank you for your awesome work on this project. :pray: This is truly the best diff tool I found on the terminal!

This is more of a question and maybe an idea of improvement.

Regarding the way the project handles syntax files, I find it peculiar that the syntax definitions are all stored in a single binary file `etc/assets/syntaxes.bin`. Why not store the syntax files in human-readable configuration files? For example, storing the syntax configuration in something like `~/.config/delta/syntaxes/my-syntax.{toml, yaml, config}` and having the following configuration in `~/.gitconfig`
```
[delta]
    syntax-theme = my-syntax
```

This way it would be more flexible and anyone could plug in any syntax file that is then read by **delta** directly from a configuration file.

In particular, it would be easy to support all base16 colorschemes by generating config files under `~/.config/delta/syntaxes/`.

**Comment by dandavison** [comment]
Hi @tgy, thanks!

OK, so you probably know this but the binary files containing the syntax-highlighting theme definitions (and language syntax definitions) both come from the [bat](https://github.com/sharkdp/bat) project. So you can indeed create your own custom theme and syntax files under `~/.config` (follow the links at [README#supported-languages-and-themes](https://github.com/dandavison/delta#supported-languages-and-themes) to the bat documentation).

 So one answer to your question is that so far in working on delta I have not revisited the decision to do anything differently from bat. I assume the reason they are stored in a binary file is to optimize the speed of accessing the required themes and syntaxes at runtime, since for good UX speed is critical for both bat and delta.

> In particular, it would be easy to support all base16 colorschemes by generating config files under `~/.config/delta/syntaxes/`.

Maybe you could expand on this, i.e. can we be explicit about what is making this not easy today via the above custom theme mechanisms?

**Comment by dandavison** [comment]
@tgy should we close this?

**Comment by tgy** [comment]
Hi @dandavison,

Thank you for your lengthy answer, to which I regret not having taken
the time to reply. My apologies.

Your clarifications helped me installing new themes and better
understand how syntaxes and themes were handled by delta.

In light of this, I don't think my initial remarks are relevant.

Thus, I'm closing the issue.

Thanks again for your work on this project! Using it everyday and my
eyes thank you very much for the more parsable / readable diffs. ;-)
