### ISSUE TITLE
delta does not seem to recognise `*.resource` files, bat does

### ISSUE THREAD

**Issue by stdedos** [dandavison/delta#415]
I pushed bat to fix the `*.resource` files highlighting (https://github.com/sharkdp/bat/issues/1386)

However, delta does not seem to recognise them.
Should it be treated as similar or separate project from bat in this case? (because I've seen https://github.com/dandavison/delta/issues/116)

I tried to set `pager = bash -c 'DELTA_PAGER=bat delta'` just in case it helped, but it didn't.

**Comment by dandavison** [comment]
Thanks @stdedos. Is the issue here that delta does not yet support "map-syntax" functionality like bat does? The most relevant issue would then be https://github.com/dandavison/delta/issues/326

**Comment by stdedos** [comment]
I don't know how delta works, so I don't know what the problem is 😄 

Hopefully my explanations were enough to pinpoint the problem.

**Comment by dandavison** [comment]
Right sorry! I think what I'm asking is: which of the following is true?

1. `*.resource` is a new "language" that bat supports but delta does not
2. bat does not support this language out-of-the-box, but bat can be induced to support it by using map-syntax declarations in the bat config file

If (1) then the fix is to update the binary language syntax assets in the delta repo and re-release. If (2), then the fix is for delta to acquire map-syntax functionality.

Delta does not use bat at run time in any way. However, delta does use the same format binary syntax and theme files that bat supplies; they are distributed as an independent copy along with delta. Delta does not respect bat's config file, but delta does respect local custom themes and syntaxes.

**Comment by stdedos** [comment]
I think if you opened the linked bat ticket you would get a more accurate response.

What I understand is: Whoever wrote the "RF Sublime language support", forgot to/intentionally(?) did not add the `*.resource` files together with the `*.robot` files. Ignoring the option to fix the upstream, the easiest option to support/fix this is the (2) option.

**Comment by dandavison** [comment]
OK, so I think we can close this as being something that will be fixed by #326 (provide a map-syntax feature for delta). I do also update to the latest theme/syntax definition files from bat with every delta release. Thanks for pointing this out and adding weight to the need to implement #326.
