### ISSUE TITLE
🚀 syntax-highlight 'git blame' output

### ISSUE THREAD

**Issue by phil-blain** [dandavison/delta#426]
Hi @dandavison ! searching "blame" in the issues brougt me to this one, but here is one (crazy?) idea:

delta could syntax-highlight `git blame output` ! that would be really great. What do you think (I can open a new issue for that if you like) ?

_Originally posted by @phil-blain in https://github.com/dandavison/delta/issues/291#issuecomment-737411832_

**Comment by dandavison** [comment]
One thing we could do here is, if the user has `hyperlinks = true` have the commit hash be a hyperlink. By default, this could be to a link to the correct line number of the correct commit in the remote web-hosted repo.

**Comment by dandavison** [comment]
I've merged initial support for this into master. Thanks @phil-blain for the feature request a while back! 

It's controlled by the new options below. At the moment, each commit gets assigned a color from `blame-palette` and every line gets shaded with the commit's color as its background color. So you'll probably want to play with `blame-palette`, especially if you're using a dark background, because the defaults are currently light. I'll probably improve the defaults and other things related to the colors before releasing this, e.g. add a light default and dark default, etc.

This is still rough so suggestions and feedback welcome.

cc @Kr1ss-XD @ulwlu @davidmnoll

```
--blame-format <blame-format>
    Format string for git blame commit metadata. Available placeholders are "{timestamp}", "{author}", and
    "{commit}" [default: {timestamp:<15} {author:<15} {commit:<8} │ ]
--blame-palette <blame-palette>
    Background colors used for git blame lines (space-separated string). Lines added by the same commit are
    painted with the same color; colors are recycled as needed [default: #FFFFFF #DDDDDD #BBBBBB]
--blame-timestamp-format <blame-timestamp-format>
    Format of `git blame` timestamp in raw git output received by delta [default: %Y-%m-%d %H:%M:%S %z]
```


<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/131235563-bb91c8d0-901d-43ec-b6c4-1fc870c8c35d.png" alt="image" /></td></tr></table>

**Comment by Kr1ss-XD** [comment]
Thanks a lot @dandavison. It's amazing to see the pace the tool is evolving with ! :+1: 

I really like this feature, although some details would still be nice to have, such as

* time formats for _output_, other than relative (perhaps even localized ?),
* highlighting according to the commit's age, like vanilla `git blame` does when `blame.coloring = highlightRecent` is set.

I'm aware both points would require `delta` to parse the timestamps, so I'm not sure how much of a hassle that would be.

As another note, it looks like I can't get `git blame` output to be formatted by `delta` when using `blame.date` formats other than `iso`, even though I'm adjusting `delta.blame-timestamp-format` accordingly. This might well be me doing something wrong though; I haven't really investigated that yet.

**Comment by michaelblyons** [comment]
> - time formats for _output,_ other than relative (perhaps even localized ?),

Yes, please. I am really quite fond of the `--date=human` format.

> - highlighting according to the commit's age, like vanilla `git blame` does when `blame.coloring = highlightRecent` is set.

This is neat. I didn't know you could do that. The _config_ setting [is documented](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blamecoloring), but `--color-by-age` is missing from the [`git-blame` docs](https://git-scm.com/docs/git-blame).

**Comment by Kr1ss-XD** [comment]
> [...] `--color-by-age` is missing from the [`git-blame` docs](https://git-scm.com/docs/git-blame).

That flag's something I didn't know it's existing. :laughing:

**Comment by dandavison** [comment]
@michaelblyons @Kr1ss-XD thanks for the points above. Now that I look at what git offers in [blame.coloring](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blamecoloring), [color.blame.highlightRecent](https://git-scm.com/docs/git-config#Documentation/git-config.txt-colorblamehighlightRecent), [blame.date](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blamedate), [blame.showEmail](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blameshowEmail), etc, I'm starting to think that my first pass at this (in master) is doing too much.

Would it make sense to backtrack and say that delta's job here is just the following:

1. Emit the metadata section of the line unchanged, with all ANSI colors intact, and
2. Syntax highlight the code?

**Comment by michaelblyons** [comment]
Good questions, Dan. There are two things in your demo that I would miss if you went the minimal route:

- The background coloring of the code area itself.
- Trimming names.

    We have one guy with a 28-char name and it really throws the `blame` code waaaaay to the right. It's fine in log statements since I've moved the name to EOL, but for blame output, the name is first. If there was a bonus `.mailmap` for blame, I could fix it locally without offending him, but I can't check in a mailmap that tinkers with his name.

**Comment by Kr1ss-XD** [comment]
I agree to @michaelblyons with everything, including both bulletpoints, and the closing post scriptum.

1. The (background) coloring of the code area gives a nice overview on the first glance, which lines of code stem from which commits.  This point is not too important for me personally though, since we can still define custom color highlighting for the metadata column via `blame`'s own settings.
2. On the other hand, regarding the metadata formatting `git blame` only allows us to use different date formats.  Therefore I'd greatly appreciate it if the implementation you'll eventually go with would at least keep the `delta.blame-format` setting.

**Comment by zachriggle** [comment]
I was just going to file an issue for this!  Thanks @dandavison and @phil-blain!

**Comment by dandavison** [comment]
Hi @zachriggle, no problem! The current blame work is in a branch if you'd like to try it: https://github.com/dandavison/delta/pull/761. There are quite a lot of open design questions -- discussed above in this issue -- due to the fact that git itself offers many options controlling blame output. But the changes in that branch at least should offer a new enhanced blame view for users that do not have a customized blame config. Let's have discussion in this issue. All thoughts appreciated.

**Comment by zachriggle** [comment]
Thanks @dandavison!  I gave it a go, but `cargo build` doesn't seem to work for me, it's unable to find `bitflags=1.3.2` 😢 

```
~/g/delta ❯❯❯ glg -5
*   128bbc4 - (HEAD -> blame-resurrection) Merge branch 'master' into blame-resurrection (3 minutes ago) - Zach Riggle
|\
| * 9d0d7f0 - (origin/master, origin/HEAD, master) [README] add notes for screen (256color/24bit) (#768) (25 hours ago) - Kriss
| * 56c47ed - Update private Homebrew formula to 0.9.2 (fix #766) (#767) (28 hours ago) - Linda_pp
* | 6c07c1f - (origin/blame-resurrection) Document blame support in README (28 hours ago) - Dan Davison
* | 84e6c34 - Formatting (28 hours ago) - Dan Davison
```

```
~/g/delta ❯❯❯ cargo build
    Updating crates.io index
error: failed to select a version for the requirement `bitflags = "=1.3.2"`
candidate versions found which didn't match: 1.2.1, 1.2.0, 1.1.0, ...
location searched: crates.io index
required by package `git-delta v0.9.2 (/Users/zachriggle/github.com/delta)`
```

**Comment by michaelblyons** [comment]
> > * highlighting according to the commit's age, like vanilla `git blame` does when `blame.coloring = highlightRecent` is set.
> 
> This is neat. I didn't know you could do that. The _config_ setting [is documented](https://git-scm.com/docs/git-config#Documentation/git-config.txt-blamecoloring), but `--color-by-age` is missing from the [`git-blame` docs](https://git-scm.com/docs/git-blame).

Hahaha, [added in 2.34.0](https://github.com/git/git/blob/master/Documentation/RelNotes/2.34.0.txt#L345-L347).

**Comment by sparrowt** [comment]
> * highlighting according to the commit's age, like vanilla `git blame` does when `blame.coloring = highlightRecent` is set.

For anyone else who ends up here, this is now supported since https://github.com/dandavison/delta/issues/808

So if you have something like this in your global `.gitconfig` then delta will respect those colours:
```ini
[blame]
    coloring = highlightRecent

[color.blame]
    highlightRecent = "#aaaaaa" "#333333",12 month ago,white "#444444",1 month ago,white "#666666",2 days ago,white bold "#888888"
```
