### ISSUE TITLE
Allow deactivate features by command line arguments

### ISSUE THREAD

**Issue by przepompownia** [dandavison/delta#492]
Example: I have activated `side-by-side` in `~/.gitconfig` and would like to deactivate it in some usage (e.g. when run from FZF).

I did not found how to deactivate single option and to keep the rest from the config. 

Some CLI-s allows deactivating their features by adding `no-` prefix.

**Comment by dandavison** [comment]
Hi @przepompownia, you're right that this isn't obvious currently! Try this:

```gitconfig
[delta]
    features = normal-delta-usage

[delta "normal-delta-usage"]
    side-by-side = true

[delta "fzf"]
    side-by-side = false
```

Now `delta --features=fzf` will not have `side-by-side`. Does that solve it for you?

To read more about delta "custom features", see https://github.com/dandavison/delta#custom-features and https://github.com/dandavison/magit-delta/issues/13#issuecomment-754761999. You could also look at the work-in-progress user-contributed [themes file](https://github.com/dandavison/delta/blob/master/themes.gitconfig), which is implemented using custom features. 

Sorry, that it's a bit convoluted currently. Part of the issue is that the main rust CLI library doesn't yet support automatic negating of boolean flags via `--no-*` versions, see https://github.com/clap-rs/clap/issues/815.

**Comment by przepompownia** [comment]
Hi @dandavison It is good to know about using custom feature. Thanks for explaining how to use it. 

It works after upgrading from 0.4.4. to 0.5.1. Setting `DELTA_FEATURES` inside vim is enough to resolve my source problem.

**Comment by dandavison** [comment]
Great, glad that solves it for you.
