### ISSUE TITLE
🚀 Manpage 

### ISSUE THREAD

**Issue by equwal** [dandavison/delta#505]
I'd like to be able to get more information about delta from the command line using `man delta`.  One way to do this would be [GNU `help2man`](https://www.gnu.org/software/help2man/) in the `Makefile`.

This is enough to get started, though the output is a bit ugly and needs more frobbing.
```sh
help2man delta | sed 's/\x1b\[[0-9;]*m//g' | man -l -
```

**Comment by Kr1ss-XD** [comment]
**NOTE** somewhat related to https://github.com/dandavison/delta/issues/377

**Comment by equwal** [comment]
Thanks, closing

**Comment by dandavison** [comment]
Hi @equwal, thanks for this. I'm open to suggestions here; basically my approach so far has been to make sure that a user in possession of the executable can obtain all necessary documentation, without recourse to the GitHub README or `man` technology. As a result I've just stuffed everything in `--help`.

We do need to keep everything convenient for Mac and Windows users in addition to GNU/Linux. But if there were a good way to generate `man` content from the documentation then it would be great to provide instructions for `man` users to do so. Personally, I'm on a Mac, and I don't really trust `man`, or trust my understanding of it. For example, I worry that I might be looking at content that doesn't correspond to the executable I'm going to use. Also, little things, like when trying to run your command (which is cool, I didn't know about it), it looks like I'd need to install the GNU version of `man` (presumably my Mac has a BSD version).

```
~ help2man delta | sed 's/\x1b\[[0-9;]*m//g' | man -l -
man: invalid option -- l
```

**Comment by Kr1ss-XD** [comment]
@dandavison 
> `man: invalid option -- l`

```sh
help2man delta | sed 's/\x1b\[[0-9;]*m//g' | man /dev/stdin
```
should work.

**Comment by dandavison** [comment]
Right, yep not for me either, looks like `man` just uses the empty input that way.

**Comment by Kr1ss-XD** [comment]
How about

```sh
help2man delta | sed 's/\x1b\[[0-9;]*m//g' >/tmp/delta.1
man /tmp/delta.1
```
?

**Comment by dandavison** [comment]
Yes, that works, thanks. (I'm blanking on why `man <(help2man delta | sed 's/\x1b\[[0-9;]*m//g')` is empty for me though).

So that looks like a pretty good start though, as you say @equwal, it needs a bit more tweaking.

FWIW, what I use is an alias: `delta --help | less -R`. Tangentially -- it might be nice if delta could invoke a pager on the `--help` output, but I haven't looked into doing that with clap/structopt.

**Comment by dandavison** [comment]
There's some good command line workarounds for generating man-formatted text from `--help` here but I'm going to close this for now since I'm not planning on taking further action on it: don't think I want to maintain a man page independently from the main --help text and README (since man pages are really only useful on linux systems and then only when the software has been installed via a package manager and there's no risk of version mismatch between the man page and the binary). Related issues for improving the help text are #514 and #377.

**Comment by equwal** [comment]
note that I think not having a man page is mega-cringle. Closing.
