### ISSUE TITLE
🐛 Cannot show long lines

### ISSUE THREAD

**Issue by bachue** [dandavison/delta#519]
Delta version 0.6.0, installed by cargo today
Mac OS X 10.13.6

git diff

<img width="1280" alt="Screen Shot 2021-02-08 at 16 10 16" src="https://user-images.githubusercontent.com/321962/107203293-354dc700-6a36-11eb-9395-0fdf40138360.png">

For the long lines in diff view, I can see these are right arrows on the right side. 
Then when I press the right arrow, I see this:

<img width="1280" alt="Screen Shot 2021-02-08 at 16 11 43" src="https://user-images.githubusercontent.com/321962/107203314-3da60200-6a36-11eb-988d-a4f4c2322bfd.png">

I still cannot see the full long line. I think it should be a bug.

**Comment by dandavison** [comment]
Hi @bachue, this is expected behavior for `side-by-side` mode, so not a bug. HOWEVER, it would definitely be nice for delta to make it possible to see the full line, and there is a very exciting PR here that is adding line-wrapping to side-by-side mode: https://github.com/dandavison/delta/pull/515.

(I think the solution has to be line-wrapping. Simply pressing right arrow might work for the right panel, but it would not work for the left panel.)

**Comment by kaldown** [comment]
Just a quick question, is it possible for `delta` _rely_ on `less` config somehow?
For instance if I have `less -FRKX`, and something like
```
[delta]
pager = less
```
The lines would be shown as expected withing this issue (folded).

Or this is a completely different architecture and most of the features should be written standalone no matter to a different pagers like `less` one?

Thanks though.
Working without syntax for years, although using delta make my day more bright :D

**Comment by Kr1ss-XD** [comment]
@kaldown 
In general, the `LESS*` environment variables do take effect, altough `delta` processes the input and _then_ sends it to `less` (and applies some default `less` flags). That's why for example the line wrapping/chopping might be done _before_ `less` even gets the data, esp. in side-by-side mode.

I hope that makes sense :roll_eyes: ?

For example with `git diff`, the data pipe is basically `git-diff` :arrow_right: `delta` :arrow_right: `less`; you can test the pure `delta` output with e.g.

```sh
git -c delta.paging=never <subcommand>
```

**Comment by kaldown** [comment]
Ye, makes sense, thank you for clarification.
Perhaps due to features like `line-number`, it would be hard  to process output out of less.
Or why isn't there `git-diff | less | delta` pipeline?

**Comment by Kr1ss-XD** [comment]
I guess there are several reasons, one of them is probably be that `delta` alters the number of lines because it adds headers and such. You'd want to have this done first, and then divide the output into pages.

**Comment by dandavison** [comment]
@bachue Note that delta also has a `width` setting that you can use to make lines extend beyond your terminal window if you want. But in general, the solution here is going to be #515.

Thanks @Kr1ss-XD. @kaldown as @Kr1ss-XD  says, you can have any `less` configuration that you'd like in the less process that delta starts. You are also free to set `pager = less | delta` in gitconfig  to experiment if you want!

**Comment by dandavison** [comment]
@kaldown Let us know here if you have any problem configuring the less process that delta starts.
