### ISSUE TITLE
Respect gitconfig's diff.context value when invoking as "delta"

### ISSUE THREAD

**Issue by perryjiang** [dandavison/delta#543]
When using `git diff`, delta appears to respect the diff.context value. However, when I am just using delta directly, it only shows the default 3 lines of context.

**Comment by Kr1ss-XD** [comment]
Nice catch !

**Comment by dandavison** [comment]
Hi @perryjiang, thanks for this! Hm, I wonder what the correct way forwards is here. `delta file_a file_b` as currently implemented calls `diff -u file_a file_b`. I'm slightly worried that the underlying issue here is that that is a bit of a hack. `diff` and `git` are two different programs that both generate diff output. 99% of delta's functionality is aimed at git, and as you correctly point out, one would expect things like `diff.context` to be respected when doing `delta file_a file_b`.

One option would be to attempt to translate git config into a `diff -u` command line where appropriate/possible. However, that feels wrong to me. I'm not sure delta should be a translator between the `git` and `diff` command line programs.

Another option is, even when you're not in a git repo, one can do `git diff file_a file_b` right? (not sure if git always did that, I think I wasn't always aware). So, that raises the question of why delta is calling out to `diff` at all. Shouldn't the `delta file_a file_b` case be implemented as `git diff file_a file_b`? (And if so, then is there even any point in having `delta file_a file_b`?) If people explicitly require `diff -u` output (as opposed to the closely related `git diff` output) then shouldn't they be using `diff -u` explicitly?

Any thoughts?

```
$ git diff a b | less
diff --git a/a b/b
index d00491f..1191247 100644
--- a/a
+++ b/b
@@ -1 +1,2 @@
 1
+2
```

```
$ diff -u a b
--- a   2021-03-18 10:35:30.943896439 -0500
+++ b   2021-03-18 10:35:35.375603284 -0500
@@ -1 +1,2 @@
 1
+2
```

```git diff a b```
![image](https://user-images.githubusercontent.com/52205/111656266-5d200f80-87d8-11eb-8bda-38a9c33c5847.png)

**Comment by perryjiang** [comment]
Ah, I actually didn't know you could `git diff` files not tracked by git. I think it's reasonable and definitely preferable to rely on only one diffing implementation, and `git diff` would be the better (and probably required) choice. I would imagine that since the primary target is `git`, any feature used available from `diff` is also available from `git diff`, in which case I don't see a compelling reason to also use `diff`. I would say this is also a good enough reason to have anyone requiring `diff -u` output to run `diff -u` explicitly.

Then if `delta file_a file_b` is just an alias of `git diff file_a file_b`, I guess it would arguably be unnecessary to have that alias, but it feels weird to me to _not_ have the `delta` alias because it would give me the idea that delta is exclusively used for git (this is pretty subjective though).

**Comment by dandavison** [comment]
Thanks, it sounds like we agree then. @Kr1ss-XD any opinions? I'm thinking that this is leading to a PR where we swap out the call to `diff -u` with one to `git diff`. Of course I hope that there aren't users who were relying on it being the former.

**Comment by Kr1ss-XD** [comment]
No, I don't have any string opinions, actually. I almost never use delta directly.

>swap out the call to diff -u with one to git diff

I do think think though that this would make sense.
