### ISSUE TITLE
🐛 [Error] Invalid charset name

### ISSUE THREAD

**Issue by sujitawake** [dandavison/delta#589]
I've installed the delta v0.7.1 on a Windows box. Whenever I use the delta command to diff between 2 text files, each time I come up with an error message saying the below error:

```
invalid charset name
error: Found argument '-u' which wasn't expected, or isn't valid in this context
```

Also attached the screenshot below for reference. Any idea what might be causing this?

![err](https://user-images.githubusercontent.com/50439521/117108975-953bdb80-ada1-11eb-8d69-50aa3b339d65.jpg)

**Comment by dandavison** [comment]
Hi @sujitawake, thanks for this. It's happening because delta is trying to call `diff -u` and that's not working with the diff program you have installed. However, don't rush to change your diff program! I'm planning to change delta so that it uses `git diff` instead: that work is discussed in https://github.com/dandavison/delta/issues/543. There's a PR here https://github.com/dandavison/delta/pull/546 which I need to revisit; I don't recall off hand why I haven't merged it yet.

**Comment by dandavison** [comment]
To be clear though, the main way to use delta is by setting it to be the pager used by git. There's an example of how to configure it here: https://github.com/dandavison/delta#deltas-main-features-are.

I'll close this now since problem on Windows should be solved by #543.

**Comment by dspvvy** [comment]
same appeared independent on kind of shell
```shell
nu: delta --help
invalid charset name
```
```
nu: delta --version
delta 0.18.2
```

**Comment by ryan-nguyen-seamless** [comment]
For some reason, re-isntalling git works for me (git version 2.51.0.windows.1).

I only had trouble with delta as a default pager for git. If I piped git diff to delta explicitly, it worked fine.

**Comment by dspvvy** [comment]
for old versions of delta setting specific path of less helped, 'cause terminal environment could use wrong version of less for bat
(like less **382** version instead of **679**):
*~/AppData/Roaming/bat/config:*
```
--pager="~/AppData/Local/Microsoft/WinGet/Links/less.exe"
```
