### ISSUE TITLE
🐛 Cannot display `hg help diff` when using delta

### ISSUE THREAD

**Issue by Alphare** [dandavison/delta#594]
If using `delta` with Mercurial, the help of `hg diff` gets truncated to only one like.

```shell
$ hg help diff
hg diff [OPTION]... ([-c REV] | [--from REV1] [--to REV2]) [FILE]...
```

I'm guessing it's seeing the line that starts with `diff` right after and thinking it's viewing a diff, when it's - in fact - not. As said in #117, the correct approach with Mercurial would probably be some kind of `extdiff` hook, which would make delta not rely on a pager hack to work. But that might be too much work for right now, and possibly there is a simple workaround.

**Comment by dandavison** [comment]
Hi @Alphare, yes, as you say, it's the line starting with `^diff `. I think, ultimately, the issue here is that the whole idea of setting  `core.pager=delta` is very questionable. Delta is not intended to be a general pager, and indeed, behaves oddly!

```
~ echo 'hello\nbye' | delta 
hello
bye
~ echo 'hello\ndiff \nbye' | delta
hello
```

I never really thought about it when I started delta -- that was how diff-so-fancy did it, and so I started off doing the same. But I'm starting to wonder if the recommended configuration for delta should be to leave `core.pager` alone, and instead set something like ([gitconfig docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt-pagerltcmdgt)) this:

```gitconfig
[pager]
    diff = delta
    log = delta
    reflog = delta
    show = delta

[interactive]
    diffFilter = delta --color-only
```

Does mercurial config support per-verb pagers like that?

**Comment by dandavison** [comment]
Hi @Alphare, I'm going to close this, because it sounds like you have an idea of the way forwards, and I believe the correct solution here for git is not to allow delta to be the pager in effect when showing help text. For git, I am going to recommend the solution above of setting the pager at the subcommand level. I'm happy to discuss how to make it work with mercurial and be of help if I can, and possibly accept non-git-oriented patches if they are unobtrusive, but to be clear I should acknowledge that it is not an explicit goal for delta to support any version control system other than git.
