### ISSUE TITLE
delta 0.8 breaks diffing fds🐛 

### ISSUE THREAD

**Issue by salmankhilji** [dandavison/delta#626]
The following no longer works with delta 0.8:

```
$ delta <(echo a) <(echo b)

dev/fd/63 ⟶   dev/fd/62
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

───┐
1: │
───┘
pipe:[128211]
\ No newline at end of file
pipe:[128213]
\ No newline at end of file
```

It used to be fine with 0.7:

```
$ delta <(echo a) <(echo b)

comparing: /dev/fd/63 ⟶   /dev/fd/62
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

───┐
1: │
───┘
a
b
$ 
```

**Comment by dandavison** [comment]
Thanks @salmankhilji. `delta file_a file_b` was recently changed to call out to `git diff` under the hood (previously it called out to `diff -u`). I was unaware of this but, as you point out, `git diff` does not seem to work with shell process substitution syntax. There's some discussion of that here: https://stackoverflow.com/questions/22706714/why-does-git-diff-not-work-with-process-substitution.

However, the error that I get (and that is in that SO page) is different from your error message, and I don't know why that is. I see this (in bash and zsh):

```
$ delta <(echo a) <(echo b)
error: /dev/fd/63: unsupported file type
fatal: cannot hash /dev/fd/63
```

The motivation for moving delta away from `diff -u` is in this discussion: https://github.com/dandavison/delta/issues/543 It seems that, unless we reverse the decision to switch to `git diff`, we will need to wait for this to be fixed upstream in git.

**Comment by salmankhilji** [comment]
@dandavison :  IMHO, a tool like delta should be as independent as possible.  A dependency on `diff` would be preferable over a dependency on `git` as the former is installed on many more machines than `git` is.  Though I agree that the target audience of `delta`, mainly developers, are likely to have `git` installed anyway.

Is it possible to detect that `delta` is being invoked by git?  If yes, `delta` could then switch over to using `git` under the hood.  Many programs set an environment variables when invoking other programs, and I assume `git` does the same.

Another option is to respect an environment variable that makes delta use `diff` under the hood.

I use `delta` in my workflow within the following function:

```
write-file() (
  local -r dst="$1"; shift || return
  local -r src="$1"; shift || return

  if [[ -f "${dst}" ]]; then
    local -r tmp="$(mktemp)" && trap "rm -f '${tmp}'" EXIT || return
    cp "${src}" "${tmp}"
    if delta --side-by-side --paging never --width "$(tput cols)" "${dst}" "${tmp}"; then
      echo -e "\e[36m=\e[0m Already up to date: \e[36m${dst}\e[0m"
    else
      echo -e "\n\e[33m≠\e[0m File contents changed: \e[33m${dst}\e[0m\n"
      cp -i "${tmp}" "${dst}"
    fi
  else
    cp "${src}" "${dst}" && echo -e "\e[94m✓\e[0m Successfully wrote: \e[94m${dst}\e[0m"
  fi
)
```

The purpose of this routine is to show a diff of the file being overwritten.  I use it like this:

```
    write-file .vscode/settings.json <(cat <<-'EOF'
			{
			  "files.exclude": {
			    "packages/parent": true,
			    "packages/app1": true,
			    "packages/app2": true,
			    "packages/shared": true
			  }
			}
			EOF
    )
```

As you can see, my workflow is independent of `git`.

**Comment by salmankhilji** [comment]
I went through #543 again, and it seems like different people have different expectations.  I expect that delta, being a unix tool, does one thing and does it well, and is agnostic of other tools to the extent possible.  If I want it to show different number of context lines, I'd pass a command line option to configure it so.  I think the original issue could have been fixed using a new command line option (if one didn't exist already) that could be added within the `git difftool` configuration within `.gitconfig` file to pass to `delta`.

I think I posted above part of my workflow that still works as that function creates a tmp file.  What is broken is the following function, which updates `/etc/hosts` file on an Android device:

```bash
#!/bin/bash
set -euo pipefail

OLD="$(adb shell cat /etc/hosts | tr -d '\r')"

HOST="$(hostname -I | cut -d' ' -f1)"

NEW="$(
  echo "${OLD}" |
  sed -E -e '/^\S+(\s+dev\.box)$/{s//'"${HOST}"'\1/;:a;n;ba;q}' -e '$a'"${HOST}  dev.box"
)"

[ "${OLD}" = "${NEW}" ] && { echo '/etc/hosts: Already up to date.'; exit; }

adb remount >/dev/null

echo -e '\e[1m/etc/hosts:\e[0m'

delta --side-by-side --paging never --width 100 \
  --hunk-header-style=omit \
  --line-numbers-left-format=░░ --line-numbers-right-format=░░ \
  --minus-style='red bold normal' \
  --minus-non-emph-style='normal normal' \
  --minus-emph-style='yellow bold normal' \
  --plus-style='green bold normal' \
  --plus-non-emph-style='normal normal' \
  --plus-emph-style='yellow bold normal' \
  <(echo "${OLD}") \
  <(adb shell "print '$(echo "${NEW}")' | tee /etc/hosts" | tr -d '\r') | sed 1,4d || true
```

**Comment by dandavison** [comment]
Hi @salmankhilji, I'm sorry delta 0.8 broke your script. And I am open to discussing adding back the option for `delta` to invoke `diff -u` rather than `git diff`. However, allow me to try to convince you that that choice shouldn't actually matter to you, since relying on it is not the right solution.

The crux is what you said:
>  I expect that delta, being a unix tool, does one thing and does it well, and is agnostic of other tools to the extent possible.

`delta` is a tool for visualization of diffs. It is not a tool for computing diffs (indeed it cannot compute diffs itself). Therefore, in order to honor the unix single-responsibility principle, delta should not offer this `delta file_a file_b` nonsense at all! It should just visualize diffs and be agnostic as to what is computing the diffs.

It only takes a small change to fix your script:

```bash
diff -u \
  <(echo "${OLD}") \
  <(adb shell "print '$(echo "${NEW}")' | tee /etc/hosts" | tr -d '\r') \
| delta --side-by-side --paging never --width 100 \
  --hunk-header-style=omit \
  --line-numbers-left-format=░░ --line-numbers-right-format=░░ \
  ...
| sed 1,4d || true
```

And furthermore, I'm going to argue that this is how your script _should_ be written. With this version we have a Unix pipeline obeying the Unix single-responsibility principle:

```bash
diff-computation-tool | diff-visualization-tool
```

In contrast, in your original version, the initial step of the pipeline was mixing up the roles of diff computation and diff visualization.  Someone in the future maintaining your script might react as follows:

> Huh, what's this "delta" thing that they're using to compute the diff? Why don't they use `diff -u`? And why does it have all these weird options for visual display of diffs if it's a diff computation tool? And anyway, how do I know that this delta thing behaves the same as diff in terms of the shell exit codes produced in the case of empty/non-empty diff?

I added the ability to pass file arguments to (`delta file_A file_B`) as an afterthought, because I thought it was fun, and with the intention that it might save some typing in interactive command line usage: but the primary way to use delta was always as a git pager, and/or to send diffs to it on stdin.

There's another reason that `delta file_A file_B` shouldn't be used in scripts: it makes it hard to control the `diff` executable being used. It would be much clearer to write `/somedir/bin/diff -u ...` than to write `PATH="/somedir/bin/diff:$PATH" delta ...`.

There are a couple of things you wrote above that I didn't quite agree with:

>  If I want it to show different number of context lines, I'd pass a command line option to configure it so.

`delta` is not a diff computation tool. Therefore it should not have command line options to control the number of diff context lines: those command line options belong in `diff` and `git diff`.

> I think the original issue could have been fixed using a new command line option (if one didn't exist already) that could be added within the `git difftool` configuration within `.gitconfig` file to pass to `delta`.

The problem in #543 was that someone was running `delta file_A file_B`, so delta was not operating as a `git difftool`. The diffs being thus produced did not respect their git config, whereas normally (when used as a git pager) delta was respecting the `git config`. This was a reasonable complaint: although it it possible to use delta purely with its command line options, by far the most common way to configure delta is by using a `[delta]` section in gitconfig (indeed there is no such thing as a `delta` config file; `~/.gitconfig` plays this role), and therefore it is understandable that someone would expect `delta` to honor the `diff.context` value in gitconfig, since it appears to do so whenever they delta is invoked by git.

Similarly

> Is it possible to detect that delta is being invoked by git? If yes, delta could then switch over to using git under the hood.

What we are discussing here is the `delta file_A file_B` form of using `delta`, and in this form it is not being invoked by git.

An argument can be made that delta should not offer this form at all. But if we offer it, then we need to choose which tool will perform the diff computation. I initially chose `diff -u`, since I was unaware that `git --no-index` was an option. But subsequently I changed that to the latter, since `delta` already has a very close relationship with `git`. But the key point is that this shouldn't matter in scripts, because there one should send diffs to delta on stdin (whether from `git` or `diff`). 

I hope I convinced you!

**Comment by salmankhilji** [comment]
Thank you for your input!

I have tried your suggested mods to my script.  The issue is that these changes will _always_ print output from `delta`, whereas I want to print this output _only_ if there were any changes to the file on the remote machine.

The appears that I can not prevent a command from executing within the pipeline provided that the previous command in the pipeline failed.  Still looking for a solution...

**Comment by salmankhilji** [comment]
Your suggestions to my script works beautifully!  Thanks :)

**Comment by dandavison** [comment]
Excellent, happy to hear that. I didn't test it out to check that the correct exit status was coming through from the correct process in the pipeline, but I was you had `pipefail` set in your script.
