### ISSUE TITLE
🐛 mouse scrolling doesn't work in "git diff", works in "git diff|delta"

### ISSUE THREAD

**Issue by indeyets** [dandavison/delta#630]
delta: 0.8.0
git: 2.32.0
less: 581.2
terminal: iTerm2 3.4.8

I set up delta as git's pager following intructions in Readme. I tried to look at some diffs and delta shows, I can control it from keyboard, but mouse-scrolling doesn't work.

I tried following advices from readme and from bat's readme but it didn't change anything.

I tried piping "git diff …" into delta explicitly and mouse-scrolling started to work.

I'd like to provide more details, but I don't know where to look. can I debug this somehow?

**Comment by dandavison** [comment]
Hi @indeyets, hm, let's try to figure it out. The first observation is, of course, that mouse scrolling functionality is determined purely determined by the behaviour of `less`, since that is the application that we are interacting with. So it seems that somehow, your `less` process is different when `delta` is being invoked by `git` versus when you are piping into `delta`. However, I am currently failing to come up with a good theory as to why that might be. Windows users sometimes get in a situation where git arranges for a different less executable to be invoked, but I can see you are on MacOS (since you are using iTerm2).

In any case, perhaps one way to investigate would be to experiment with explicitly specifying the pager when delta is invoked by git. I'm thinking of things like  this perhaps:

```
- delta (master) git -c pager.show='DELTA_PAGER="echo testing" delta' show
testing
- delta (master) git -c pager.show='DELTA_PAGER="/usr/bin/local/less -R" delta' show
# shows real output
```


It sounds like you've already seen the places where there is some discussion of the relevant `less` options, i.e. #58 in particular. There's also this comment in that ticket: https://github.com/dandavison/delta/issues/58#issuecomment-703770458

**Comment by indeyets** [comment]
@dandavison I see the same output as as you show. so DELTA_PAGER does work. but mouse-scrolling doesn't work :-(
even if I specify `--mouse`

could it be some weird subshell limitation?

I didn't mention, that my main shell is fish.

I just did another experiment: I started zsh from fish and tried running commands there. mouse doesn't work at all. even in piping scenario.

**Comment by dandavison** [comment]
Hm, curious. It's mainly a terminal emulator thing isn't it, but it does sound as if there's some correlation with the pager being invoked as a more deeply nested child process. Perhaps there could be an environment variable being set by the shell which influences this behaviour.

I think it would be good at this stage to experiment with `less` directly, taking `delta` out of the picture. If you set `pager.show=less <options>` can you reproduce your observation that scrolling works when piping input to `less` but does not work when `less` is invoked by `git`?

A trick to investigate the environment variables that the process invoked by git sees is `git -c pager.show=env show`. Perhaps compare that output to the normal output of `env`.

Are you using tmux? (If so, could you try without). And could you maybe try some experiments in a different terminal emulator (e.g. the default MacOS Terminal.app).

**Comment by indeyets** [comment]
no tmux
Terminal.app — everything's exactly the same. :-/

will try other suggestions a bit later. thank you!

**Comment by Kr1ss-XD** [comment]
@indeyets - If you could post the output of 
```sh
!env | grep LESS\|DELTA\|PAGER
```

executed from inside the pager, once opened via `git diff` and once via `git -P diff | delta`, that might give us some clue.

What I mean is, please execute that command 
* from a `less` instance where the mouse works, and
* from another one where it doesn't.

Just to see if the output is different.

What also comes to my mind is, in case that you are using a `.lesskey` file ([ref](https://www.tutorialspoint.com/unix_commands/lesskey.htm "lesskey(1) manual")), that might have weird side-effects with {git,delta,bat,some-other-app-that-invokes-less}.

**Comment by indeyets** [comment]
There are no env-vars in both cases, but there's difference!

`git diff` (where mouse doesn't work) gives me this (command and result are appended to diff output):

![newfront-ui 2021-06-12 01-50-34](https://user-images.githubusercontent.com/13445/121755742-9ee2fc80-cb20-11eb-8d6d-816639f17a51.jpg)

`git -P diff | delta` (where mouse works) gives me this (output is hidden and only result of command is on screen):

![newfront-ui 2021-06-12 01-53-24](https://user-images.githubusercontent.com/13445/121755875-fc774900-cb20-11eb-9742-0f117530ea4c.jpg)

**Comment by indeyets** [comment]
and yes, @dandavison, I can reproduce this with raw less :-/

**Comment by dandavison** [comment]
Ah-ha! I'm off the hook 😅 . No, seriously, happy to carry on chatting here.

**Comment by Kr1ss-XD** [comment]
Thanks for checking @indeyets !  Let's see what we have.

Since in the first screenshot, we see the `less` output while we don't in the second one, I think that `less` is given some arguments when invoked via `git`. This probably happens due to the git configuration.

If I'm correct, you should be able to get your mouse wheel working by adding : 
```gitconfig
[core]
	pager = less -LRc --mouse

[pager]
	diff = LESS='LRc --mouse' delta
	show = LESS='LRc --mouse' delta
	stash = LESS='LRc --mouse' delta
	log = LESS='LRc --mouse' delta
	reflog = LESS='LRc --mouse' delta
```

to your [git configuration](https://gitirc.eu/git-config.html#FILES "git config files - locations").  Note that if one of the section headers `[core]`/`[pager]` (or both of them) is/are already present, you don't need to repeat it; just add the indented line(s) to the according section in this case.

If there is already a `pager = ...` line inside the `[core]` section, you can either
* replace this line with my suggestion,
* comment it out by prefixing it with a `;` semicolon and add the new definition.

The same applies accordingly if there are already `diff`, `show`, `stash`, `log` or `reflog` lines in the `[pager]` section.

I hope this helps !

**Comment by indeyets** [comment]
@Kr1ss-XD wow! it did the trick. thanks a lot!

@dandavison I hope it will be useful for someone else :-D

**Comment by Kr1ss-XD** [comment]
Nice ! :+1:

**Comment by dandavison** [comment]
> @dandavison I hope it will be useful for someone else :-D

Definitely. This ticket has lots of helpful information. Thanks @Kr1ss-XD for that solution!

**Comment by ucomru** [comment]
> If I'm correct, you should be able to get your mouse wheel working by adding :
> ```gitconfig
> [core]
> 	pager = less -LRc --mouse
> 
> [pager]
> 	diff = LESS='LRc --mouse' delta
> 	show = LESS='LRc --mouse' delta
> 	stash = LESS='LRc --mouse' delta
> 	log = LESS='LRc --mouse' delta
> 	reflog = LESS='LRc --mouse' delta
> ```

It's worked OK! I had same problem. 
As Im understand, the problem with `--mose` key at `LESS` variable.
By default `LESS=-R`.
I think the most simplest way is to set at `~/.zshrc` less variable: 

```sh
export LESS='-R --mouse'
```

It will be worked at pure iTerm and inside tmux session to.

**Comment by evan-goode** [comment]
> export LESS='-R --mouse'

This fixed the issue for me. Maybe this could be mentioned in manual/src/tips-and-tricks/mouse-scrolling.md?

**Comment by RWOverdijk** [comment]
Anyone landing here in 2026, what worked for me is adding `pager` to `~/.gitconfig`:

```.gitconfig
[core]
  editor = nvim
  pager = less -RF --mouse
```
