### ISSUE TITLE
🚀 Pre-load pager ("less") search term to be able to jump to the next change

### ISSUE THREAD

**Issue by zachriggle** [dandavison/delta#640]
Hello!  I love `delta` and all of its features, it really has improved my life when reviewing patches.

However, when I review patches, I generally use `git log -p -W`, which shows the whole function context.  Occasionally, Git gets confused (or is perhaps right) and displays the ENTIRE contents of the file.  Even if it's right, sometimes it would be useful to have a magic "jump to the next change" search query pre-loaded into `less`.

Navigating manually through all of this can be slow, but the context is generally useful enough that I leave the `-W` feature enabled.

The man page for less describes the `-p` / `--pattern` flag:

```
       -ppattern or --pattern=pattern
              The -p option on the command line is equivalent to specifying +/pattern;
              that is, it tells less to start at the first occurrence of pattern in
              the file.
```

This also pre-loads the search buffer, so you can move to the next match with `/<enter>`.

It would be neat if `delta` could pre-load this with an expression that is something like `commit |<magic>` where `<magic>` is some byte sequence that matches the `+/-` or background-red-green-highlighted sections.  This makes it easy to jump to the next commit, or change within the commit.

**Comment by Kr1ss-XD** [comment]
Hi @zachriggle !

If I don't completely misunderstand your comment, there is a [feature](https://github.com/dandavison/delta#navigation-keybindings-for-large-diffs) that seems to be what you're looking for. If called as `delta --navigate`, or if `delta.navigate = true` is set via `gitconfig`, you can jump between the diff hunks and commits with less' `n`/`N` key bindings.

**Comment by zachriggle** [comment]
@Kr1ss-XD This does work by inserting a special capital-∂ (`Δ`) character at the beginning of each commit and each modified filename, but does not work for navigating between modified chunks within the file.

This is particularly useful / important when using e.g. `--function-context` for `git log -p`, which shows the ENTIRE function for any modified function.

Some of these are quite large, and being able to jump to the next series of changes (which may be in the same file, very far away) is a feature that `--navigate` does not help achieve.

I've even tried without `--function-context` and `--navigate` with n/N just jumps to the next commit / file, not the next sequence of changes.

**Comment by dandavison** [comment]
Hi @zachriggle! Thanks for the kind words about delta. My initial answer was the same as @Kr1ss-XD's but, right, I understand your proposal. I am wondering whether it might work to allow the navigate regexp to be fully user-customizable.

> an expression that is something like `commit |<magic>` where `<magic>` is some byte sequence that matches the `+/-` or background-red-green-highlighted sections. 

So one thing is that I think that `less` is performing its regex search on a version of the text with the ANSI color escape sequences stripped out. Would you agree? For example, `0\.8\.1` matches this (using `/` to search)
<table><tr><td><img width=150px src="https://user-images.githubusercontent.com/52205/123509001-e7df9880-d66a-11eb-8234-109ce9a04bf4.png" alt="image" /></td></tr></table>
despite the change in background color. If that is so then that threatens to make it impossible to search for red/green.  But we could use `keep-plus-minus-markers` to give it those anchors to search for.

Here's a command that you can use right now without any changes to delta to experiment with that:

```
LESS='-R --pattern=^[\+-]' git -c pager.log='delta --keep-plus-minus-markers' log -p
```

Can you let me know whether you can find a regex that works well for you in `less` to do the navigation you want? I'd be happy to add a new delta option like `navigate-regex` to allow a custom regex to be used in place of the default. Which, by the way, is this: https://github.com/dandavison/delta/blob/a4f5a4fa686a8db72afbb4f07ae906effbf0fe8e/src/features/navigate.rs#L37-L40
(and you can use the delta options `file-modified-label`, `file-removed-label`, `file-added-label`, `file-renamed-label` to pick your own word or symbols instead of `Δ` etc).

**Comment by dandavison** [comment]
@zachriggle did the less pattern I suggested above work for you? Here's what it looks like in action:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/130339160-e90037c7-440a-458d-8a4a-72c21572a332.png" alt="image" /></td></tr></table>

Re-reading this ticket, there's one thing that doesn't seem accurate:

> This does work by inserting a special capital-∂ (Δ) character at the beginning of each commit and each modified filename, but does not work for navigating between modified chunks within the file.

delta `navigate` stops at 3 places: commit boundaries, file boundaries within a commit, and hunk boundaries within a file.

So `navigate` does allow us to jump to the next change hunk. But, I think what you want is more fine-grained than that, i.e. to stop at the next change block, which delta doesn't do in the case where a hunk has multiple changes:

<table><tr><td><img width=300px src="https://user-images.githubusercontent.com/52205/130339145-d272cd0d-92d6-4451-97e1-c8541ff4e546.png" alt="image" /></td></tr></table>

But the `--pattern=^[\+-]'` trick does something similar.

**Comment by dandavison** [comment]
@zachriggle delta now has a `navigate-regex` option allowing a custom regex to be specified. So now, with

```gitconfig
    keep-plus-minus-markers = true
    navigate-regex = '^(commit|added:|removed:|renamed:|Δ|•|[\+-])'
```

`n` and `N` will stop at added/removed lines, as well as at commit/file/hunk boundaries.

Does this give you what you need? (I'm closing because I think this issue should be addressable with usage of custom `navigate-regex`)

**Comment by zachriggle** [comment]
# Kudos and thanks!

@dandavison thanks for everything, as always.  It's not clear to me that this solves the issue of hunk-searching.

Glad to be a sponsor! 🌟

# What works

Almost everything in your comment https://github.com/dandavison/delta/issues/640#issuecomment-991924062 work as expected.

I disabled all `diff` and `delta` related functionality in my gitconfig to generate this image below.

Hitting `N` or `n` correctly take to the next `^commit` or `^Δ` (modified file) as well as `^•` (hunk)

![image](https://user-images.githubusercontent.com/111640/145771925-e6e6da66-0120-4ac4-aa6a-9a8fd4976bb3.png)

# What does not

The regex that doesn't work for me is `^[\+-]` (effectively) for matching the addition / subtraction lines.  
This does not work with `--features='line-numbers decorations'`.

It might be worthwhile to add something to account for this.  While inside `less`, this expression seemed to handle the situation with `--features=line-numbers`:

```regex
^([0-9]* *)⋮([0-9]* *)\│[-\+]
```

I believe I can work around this with your custom `navigate-regex` setting, but I thought it was worth mentioning.

# Future suggestions

It would be nice if the "marker" for the beginning of a "hunk" were on the first line of the actual hunk change.  The current solution is a 97% solution, and perfect for almost everything.

However, when using `--function-context`, the (1) hunk header is incorrect and (2) when `--function-context` or `-W` are used, the actual changes can be very, very far from the first set of `+/-` changes.

There's another bug tracking (1) and it's nothing to do with `delta`'s functionality -- Git itself is wrong.

For (2), I think it would be useful to replace the `⋮` glyph separating added / removed lines with another, special character.  This would be on the first line of the hunk which actually changed.  Alternately, the `│` glyph separating line numbers from the code could be changed for the first-line-of-the-chunk-which-is-actually changed.  

In the above screenshot -- which is a terrible example of situations where this would matter -- the glyphs annotating line 1456 might be changed (and in the default regex set).
