### ISSUE TITLE
How to override the side-by-side option via git? (Question)

### ISSUE THREAD

**Issue by vizcay** [dandavison/delta#660]
Hey first of all thanks for this great utility! Something I will like to improve in my workflow is that, althought most of the time `side-by-side` is great, for some diffs I will want to turn it off.

As I have in my `.gitconfig` file
```
[delta]
    features = side-by-side line-numbers navigate
```

The only way that I've found for this will be to do:
```bash
$ git diff -c "delta.features=line-numbers navigate"
```

That is cumbersome to type.. I know this is git related, so I may be missing something easier.

Any ideas?

**Comment by Kr1ss-XD** [comment]
Hi @vizcay 

How about utilizing a git alias for that purpose : 

`~/.gitconfig` : 

```gitconfig
[delta]
	features		= sbs line-numbers navigate
	<...>
[delta "sbs"]
	side-by-side	= true
[delta "unified"]
	side-by-side	= false
<...>
[alias]
	uni				= !DELTA_FEATURES='unified line-numbers navigate' git
	< OR: >
	uni				= !git -c 'delta.features="unified line-numbers navigate"'
```

With that in place, side-by-side layout is the default. Everytime when you need unified diff output, just call git as : 

```sh
git uni log|diff|add|show|... <...>
```

Otherwise, a shell alias should also work.

`.bashrc` / `.bash_profile` / wherever in your shell startup : 
```sh
alias Git="DELTA_FEATURES='unified line-numbers navigate' git"
```

With that alias, `git` would give you side-by-side layout, while `Git` switches to unified.

**Comment by vizcay** [comment]
It works 🎉
