### ISSUE TITLE
🚀 Clean screen after quit git diff

### ISSUE THREAD

**Issue by chunyang-wen** [dandavison/delta#663]
If we do not use `delta` as the default `git diff`, the terminal will be clean again if we quit the command.
![image](https://user-images.githubusercontent.com/2911134/126252146-0c3a8efb-ec9c-45c8-893f-4893d294b611.png)
![image](https://user-images.githubusercontent.com/2911134/126252207-4c2efe25-1b67-4a89-be33-c3f2b5f205bf.png)

But if we use:
![image](https://user-images.githubusercontent.com/2911134/126251597-e8375e6b-85d5-4854-ba33-7fda177d7aea.png)
when we input a `q` to quit, the content will stay.

I just wonder if it is possible to achieve the same results as the default `git diff`.

I can call a `clear` after quit to clean the screen, but other message will also be cleaned.

**Comment by Kr1ss-XD** [comment]
Hi @chunyang-wen !

This is actually caused by `less`, not by `delta`. You appear to have different options for `less` when called via `delta`, as opposed to when it's called by `git` directly.

Without any additional information about your setup it's hard to give tangible advice, but there are several flags that influence `less`' behavior regarding clearing the screen, e.g. `-c`/`-C`, or `-X`. There's also `-F`, which prevents paging at all, if the output is no longer than a screenful. You can find descriptions of those options via `man less`, in the `OPTIONS` section, or otherwise [here](https://man7.org/linux/man-pages/man1/less.1.html#OPTIONS).

When looking for the cause of the described behavior, keep in mind that there are multiple places where `less` options might be set. Most likely this happens via the `LESS` environment variable and/or in (one of) the `core.pager = ...` resp. `pager.<command> = ...` definition(s) in your git configuration.

With that said, the following is just a shot in the dark at this point, but you could try defining : 

```gitconfig
[core]
    pager   = less
[pager]
    diff    = LESS=c delta
    show    = LESS=c delta
    log     = LESS=c delta
    reflog  = LESS=c delta
    status  = LESS=c delta
;   ...
```

I'd suggest you experiment a bit with the flags; you might find some others that are useful for your workflow.

**Comment by chunyang-wen** [comment]
Thanks @Kr1ss-XD .

I have used the default .gitconfig

```python
[pager]
    diff = delta
    log = delta
    reflog = delta
    show = delta

[interactive]
    diffFilter = delta --color-only

[delta]
    features = side-by-side line-numbers decorations
    whitespace-error-style = 22 reverse
    syntax-theme = Solarized (dark)

[delta "decorations"]
    commit-decoration-style = bold yellow box ul
    file-style = bold yellow ul
    file-decoration-style = none
```

I will test your solution.

**Comment by Kr1ss-XD** [comment]
Hmm let's see... assuming that you're on Linux (if not, pls adjust the paths accordingly), could you post the output of

```sh
env | grep -E PAGER\|^LESS\|GIT_CONFIG; grep -isE less\|delta\|pager /etc/gitconfig ~/.config/git/config ~/.gitconfig
```

Of course, if the output contains any sensitive information, please redact it.

**Comment by chunyang-wen** [comment]
```bash
/Users/hah/.gitconfig:    pager = less -R
/Users/hah/.gitconfig:[pager]
/Users/hah/.gitconfig:    diff = LESS=Rc delta
/Users/hah/.gitconfig:    log = LESS=Rc delta
/Users/hah/.gitconfig:    reflog = LESS=Rc delta
/Users/hah/.gitconfig:    show = LESS=Rc delta
/Users/hah/.gitconfig:    status = LESS=Rc delta
/Users/hah/.gitconfig:    diffFilter = LESS=C delta --color-only
/Users/hah/.gitconfig:[delta]
/Users/hah/.gitconfig:[delta "decorations"]
```

**Comment by chunyang-wen** [comment]
delta diff with `!echo $LESS`
![image](https://user-images.githubusercontent.com/2911134/126741117-aa1b1955-c3d1-4d6a-b6ed-db7c7df3bc97.png)

git -c pager.diff=less diff
![image](https://user-images.githubusercontent.com/2911134/126741143-28a838c4-951a-4b27-a93c-6d1847a80f17.png)

**Comment by Kr1ss-XD** [comment]
Well thank you @chunyang-wen for getting back.

Although, I'm afraid I'm out of ideas at this point. With the most recent config you posted, and an otherwise clean environment, it's clearly [working](https://asciinema.org/a/rl7shgx04K4f7GcXu34kMif8k) here.

Unfortunately I've got no clue on what else could be different on your end, or how we would go about creating a clean debugging setup on both sides.  Maybe @dandavison could give us a hint ?

**Comment by chunyang-wen** [comment]
I am on Macos Bigsur 11.3

**Comment by jab** [comment]
I also hit this out-of-the-box on macOS 10.15.7 after `brew install delta`, but then `brew install less` seems to have fixed it. (Looks like my system `less` was version 487; homebrew `less` is version 590.)

**Comment by dandavison** [comment]
I also think that @Kr1ss-XD's suggestions should have worked  (i.e. making sure the `-X` argument is not added by explicitly setting less options in the `LESS` env var, or `DELTA_PAGER`, or by using the `--pager` delta command line option.

And @jab 's suggestion to use a more recent less is a good one too, since the auto-add-X-option behavior is only done for old less versions (bat does the same thing).

> I also hit this out-of-the-box on macOS 10.15.7 after brew install delta, but then brew install less seems to have fixed it. (Looks like my system less was version 487; homebrew less is version 590.)

This recent issue is similar: https://github.com/dandavison/delta/issues/652

**Comment by jab** [comment]
Hm, I have been explicitly setting my `LESS` environment variable to `"-iR"` in my shell startup config for years. I still hit this issue out-of-the-box until I upgraded less.

**Comment by Kr1ss-XD** [comment]
Thx @dandavison and @jab - this shines some light onto the issue.

So the suggestion for @chunyang-wen would be to update `less` to a newer version, preferably via

```sh
brew install less
```

**Comment by dandavison** [comment]
> Hm, I have been explicitly setting my LESS environment variable to "-iR" in my shell startup config for years. I still hit this issue out-of-the-box until I upgraded less.

That might be because if it is unable to parse the less version then it assumes the version is problematic and does the force-X behavior. Sorry about this, it is a bit annoying to have to do it but I think it's fixing a real bug in a reasonably common version of less.

**Comment by chunyang-wen** [comment]
@Kr1ss-XD @jab Yes, problem solved after upgrading less. It seems that we have to Prepend less bin path to `PATH` variable in order to replace the system less, or config in `.gitconfig`.
