### ISSUE TITLE
🚀How does one integrate delta into Sourcetree ? 

### ISSUE THREAD

**Issue by SysOverdrive** [dandavison/delta#670]
Hi, thanks for contributing to Delta, please go ahead and describe your proposal!

**Comment by dandavison** [comment]
Hi @SysOverdrive, I'm not familiar with sourcetree. I think the right place for this discussion would be a sourcetree help/community forum. The answer will depend on how sourcetree is implemented. I'm happy to provide further help here from the delta side, but I'll close the issue since as far as I know there's no action needed in the delta codebase yet.
