### ISSUE TITLE
🐛 `git show COMMIT:FILE` is broken wrt syntax coloring

### ISSUE THREAD

**Issue by lelouchXzero** [dandavison/delta#673]
Hi, thanks for the tool.

If I try `git show HEAD:<changed_file>`, there is no syntax coloring. Removing the commit reference works as expected. The command works if I use `git --no-pager`, so it is not an issue with the command. Even `git -c pager.show="bat -l<LANG>" show HEAD:<changed_file>` works as expected. Any commit hash in place of `HEAD` shows the same behavior.

My gut feeling is that what is happening here is that the file type is not being communicated properly to `delta`, so it falls back to no color.

It would be great if this could be fixed.

**Comment by Kr1ss-XD** [comment]
Hi @lelouchXzero !

The command you've mentioned does not output any diff/patch, but basically just the contents of a certain file at a certain point in the repo history. I think that's the reason why `delta` simply passes the data through to `less` (or whatever the configured pager is) in this case.

Not sure if `delta` would be able to deduce the file type somehow (as far as I understand, it doesn't "see" the file name). As you've noticed, you need to specify the file type explicitely when using `bat` as the pager, in order to enable syntax highlighting.

If I'm wrong and that would be possible anyways, I agree this would be a nice feature though.

**Comment by dandavison** [comment]
Hey @lelouchXzero, @Kr1ss-XD 

Right, as @Kr1ss-XD says, delta usually infers the language from the file extensions present in the file names in the diff output. But here of course we're basically just cat'ing the file, and there is no indication what its name is.

So, what's the best way to address this? Having to specify `-l<LANG>` seems inconvenient, though perhaps if one is working in a repo with mostly files of a single language, it would be ok to have a delta option like `default-language = rs`, perhaps in the gitconfig local to that repo (although I personally haven't looked into good ways of having repo-local delta config).

Another thought is perhaps we could obtain the arguments passed to the parent git process via [sysinfo::ProcessExt.parent](https://docs.rs/sysinfo/0.19.2/sysinfo/trait.ProcessExt.html#tymethod.parent) and [sysinfo::ProcessExt.cmd](https://docs.rs/sysinfo/0.19.2/sysinfo/trait.ProcessExt.html#tymethod.cmd). But then we would be faced with the task of parsing the git command line to find the file path.

Any better ideas?

**Comment by Kr1ss-XD** [comment]
No @dandavison, at least not a better idea as to what could be done from the `delta` side.

But I think it could be doable with a either a `git` alias or a shell function that takes a commit reference and a file path as arguments, checks the file out from that commit, then opens it with `bat` and finally checks out the file at `HEAD` or whatever the state was when the function was called. (I hope that made sense.)

Not sure if it's worth the effort to implement a command line parser, but I would definitely appreciate being able to have local configurations. That could be nice for options other than `default-language`, too. :slightly_smiling_face:

**Comment by Kr1ss-XD** [comment]
Here's (kind of) a solution for you @lelouchXzero; add this to your git config : 

```gitconfig
[alias]
	bat	= !sh -c 'git -c pager.show=\"bat --file-name='$1'\" show '$*
```

After that you can run `git bat <COMMIT>:<FILE>` to get syntax-highlighted output.

This is not perfect though : 

* there's no input sanitization / error handling
* the commit-colon-filepath combination **must** be the first argument; if you need to apply any options/switches they need to be specified after this

In the long run it might be better to write a shell function which could handle more cases (argument order, different syntaxes like space instead of colon, and flexible ordering of arguments, but I guess as a starting point this git alias might still be useful.

**Comment by lelouchXzero** [comment]
Thank you for your comments and the help.
I was kind of mistaken about the tool before, I just read the README properly and realized that this tool specifically handles diff output.
Apologies for opening an out-of-scope bug!

Regarding comments made above, just my two cents:
- @dandavison I would not recommend adding a command parser, IMO this tool takes one thing and does it well. There is no need for adding that.
- @Kr1ss-XD Thanks for the solution. I am unlikely to use it due to the strict order of evaluation, but I appreciate the effort nonetheless.

**Comment by dandavison** [comment]
Thanks @lelouchXzero @Kr1ss-XD, I agree but still, when we set `show.pager=delta` we are saying that delta is to handle git show output, so I would ideally like this to work. (Personally I also use show in this way to view files as-of a certain commit). So perhaps the default language idea would be worth (someone) implementing in the future.

Alternatively, I think it could make sense for a Rust crate to exist that infers the programming language from a sample of text, similar to or https://github.com/yoeo/guesslang (python) or https://github.com/andreasjansson/language-detection.el (emacs lisp). I don't immediately see one though.

There's a related problem of how delta syntax-highlights files with no extension, that this could help with. For example that's common with scripts written in an interpreted language which are designed to be used as executables.

**Comment by Kr1ss-XD** [comment]
>when we set show.pager=delta we are saying that delta is to handle git show output

Totally makes sense.

These language-guessing projects are very interesting. In case there would be a Rust implementation at some point now or later, I'd love to see that implemented in `bat`. Just seems it belongs even more to its scope than `delta`'s.

>There's a related problem of how delta syntax-highlights files with no filename extension

FWIW, there's also #485 which might be taken into consideration, although it wouldn't be a "catch'em-all" solution.

**Comment by dandavison** [comment]
Update: since `0.10.0` delta automatically syntax highlights `git show $commit:$file.extension` output.

This works by inspecting the command line of the relevant process -- so in this case that's a git  process, and delta will see `.extension` and determine the language from that. This should always work in the usual case where `delta` is being invoked by `git` as its pager (i.e. where you have configured `delta` as git's pager in gitconfig). Delta will try to make it work in other cases, such as where you have a wrapper script around delta, and where you are piping the output to delta. But piping in particular will not always work automatically, especially if it's a small number of lines being piped (since the piping process may terminate before delta has a chance to look at its command line).

Related: in the next release, delta will additionally support a `default-language` option which can be set on a per-repo basis (`$myrepo/.git/config`) to specify a fallback language in the case of things like shell scripts with no file name extension.
