### ISSUE TITLE
🐛  Process substitution diffs pipe IDs instead of content

### ISSUE THREAD

**Issue by tullo-x86** [dandavison/delta#713]
# Description

When attempting to use process substitution, Delta appears to diff the pipe IDs instead of their contents.

## Expected behaviour
Should work like `diff` does
<img width="575" alt="image" src="https://user-images.githubusercontent.com/2888110/132728576-c9901e15-bf69-4920-83ac-2b425f308ed1.png">

#### Process output:
```
tully@serotonin ~ % diff <(lsusb -t) <(sleep 2; lsusb -t)
16a17
>         |__ Port 4: Dev 24, If 0, Class=Imaging, Driver=, 480M
1 tully@serotonin ~ %                                                                            :(
```

### 🤷🏼‍♂️
<img width="575" alt="image" src="https://user-images.githubusercontent.com/2888110/132728717-bbacd8c5-9fac-4669-a46b-6aecdf8ee040.png">

#### Process output:
```
tully@serotonin ~ % delta <(lsusb -t) <(sleep 2; lsusb -t)

proc/self/fd/11 ⟶   proc/self/fd/12
───────────────────────────────────────────────────────────────────────────────────────────────────

──────┐
Δ :1: │
──────┘
│ 1  │pipe:[1971675]                             │    │
\ No newline at end of file
│    │                                           │ 1  │pipe:[1971676]
\ No newline at end of file
1 tully@serotonin ~ %                                                                            :(
```

**Comment by dandavison** [comment]
Hi @tullo-x86, I agree, this is a frustration. Unfortunately the problem seems to lie upstream with git itself: `git diff A B` does not work when `A` or `B` are shell process substitution syntax. There's actually already an open issue for this, take a look at https://github.com/dandavison/delta/issues/666#issuecomment-886254833 where I give a link to a stackoverflow discussion, which has a link to a git bug discussion. I would love suggestions regarding how delta can move forwards here.

Let's discuss in #666 (so I'll close this one).
