### ISSUE TITLE
🚀make git diff simpler

### ISSUE THREAD

**Issue by laoshaw** [dandavison/delta#773]
to make output less verbose, can I get rid of the red-arrow line?

![xx](https://user-images.githubusercontent.com/18351761/141666340-bb3f6258-8f4c-4b3e-96eb-27664cb5a5fa.png)

**Comment by Kr1ss-XD** [comment]
Yes, absolutely. Just include this in your git configuration : 

```gitconfig
[delta]
	hunk-header-style	=	omit
```

**Comment by laoshaw** [comment]
Perfect. Thank you!

**Comment by dandavison** [comment]
@laoshaw I won't be offended if you `omit` it :) But just in case this isn't clear -- or for anyone else reading this -- in general the hunk header displays the "function context", i.e. the function/class etc in which the code change occurs. It's not a delta feature -- it's in standard git diff output. Here's what it looks like in delta with my personal config:

<table><tr><td><img width=600px src="https://user-images.githubusercontent.com/52205/141691749-7d58c094-ec89-40b6-ba53-f9a1cfcde237.png" alt="image" /></td></tr></table>

In addition to telling us what function the change is in, in many terminal emulators you should be able to click (e.g. ctrl+click) on the `/path/to/file.c:77:` file+line-number construct and have it open in your editor. (E.g. that works out-of-the box in the VSCode terminal).

Another advantage that you may like is that if you activate `navigate` then pressing `n` and `N` will navigate forwards and backwards to the next/previous diff hunk (using the `•` marker you see there).

In your case, the one in your screenshot is a "boring hunk header" -- it only shows a line number because there is no function context, and so it is indeed rather pointless:

<table><tr><td><img width=100px src="https://user-images.githubusercontent.com/52205/141691964-21f2c015-e5df-448c-acbf-64c2b4b2a186.png" alt="image" /></td></tr></table>


**My config**

```gitconfig
    navigate = true
    hunk-header-decoration-style = blue box
    hunk-header-file-style = red
    hunk-header-line-number-style = "#067a00"
    hunk-header-style = file line-number syntax
```

**Comment by laoshaw** [comment]
Thanks! Just found out delta yesterday, and yes I might bring the hunk-header back :)
