### ISSUE TITLE
🐛 Colored output for `git blame --color-by-age` not working with delta.

### ISSUE THREAD

**Issue by AjayKMehta** [dandavison/delta#808]
First off, thanks for developing this amazing tool that I use daily!

I was excited to read about v 0.10 supporting `git blame` so I decided to try it out. My `.gitconfig` looks like this:

```ini
[core]
	pager = less -rFX
...
[blame]
	coloring = highlightRecent
...
```

`blame.coloring = highlightRecent` causes [`git blame` to color line annotations depending on the age of the line](https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---color-by-age).

`git blame` output looks like this:

![git-blame](https://user-images.githubusercontent.com/11180071/143779088-e0b5b3cf-a64e-41e2-a986-7867ad96214e.png)
 
Specifying, `-c core.pager=delta` causes line annotations to be stripped of their color:

![git-blame-delta](https://user-images.githubusercontent.com/11180071/143779125-f6ff7e96-3d73-484c-934a-440288b9d6cc.png)

I am not sure if this is by design but would it be possible to retain line annotations' color in `git blame` output when using `delta`?

Thanks!

**Comment by dandavison** [comment]
Hi @AjayKMehta, thanks for this. Yes, absolutely, it is fixed in master now -- if you're able to [build from master](https://github.com/dandavison/delta#build-delta-from-source) and try that would be great of course. If the `blame-format` contains a dividing line as it does by default then it may look a little strange, since the dividing line will be multi-colored. We'd have to make the dividing line separately configurable or hard-coded I think to solve that.

**Comment by AjayKMehta** [comment]
@dandavison I don't have the Rust tools installed. As for the dividing line being multi-colored, that is OK IMHO.
