### ISSUE TITLE
🐛 Syntax highlighting incorrect when using one line comment (java)

### ISSUE THREAD

**Issue by krei-del** [dandavison/delta#864]
Hi,
this is little bug, but not too problematic. The grey color highlighting for a one line comment continues  after the comment line:

![image001](https://user-images.githubusercontent.com/67123155/146791068-faa9111b-ea18-4262-99b7-55677c6ba6a2.png)

**Comment by dandavison** [comment]
Hi @krei-del, hm, that shouldn't happen. Would you be able to prepare a text diff that reproduces this bug (i.e. so that we can do `delta < diff.txt` and see the bug)?

For example, I cannot reproduce it with this:

```diff
diff --git a/file.java b/file.java
new file mode 100644
index 0000000..401fc72
--- /dev/null
+++ b/file.java
@@ -0,0 +1,6 @@
+        if (hasVariante(RULE_ID, TABLE_ID, COLUMN_ID, VARIANTE_0)) {
+            // Feld wird nicht ausgegeben
+            if (theCurrentColumn.getMetaData().isIgnoreOutput()) {
+                something();
+            }
+        }
```

<table><tr><td><img width=500px src="https://user-images.githubusercontent.com/52205/146809964-ce0ae497-3dcb-46df-9b3b-1f3306170d2a.png" alt="image" /></td></tr></table>

**Comment by krei-del** [comment]
Sorry, I should have created a diff.txt  at first place .. now the code evolved and currently I can't reproduce the error. Maybe we reopen this bug at later point in time.
