### ISSUE TITLE
🐛 Incompatible with binary caches from latest bat

### ISSUE THREAD

**Issue by kidonng** [dandavison/delta#895]
bat recently released a new version [v0.19.0](https://github.com/sharkdp/bat/releases/tag/v0.19.0), after updating I got the following error when using bat:

```
The binary caches for the user-customized syntaxes and themes in '/path/to/cache' are not compatible with this version of bat (0.19.0). To solve this, either rebuild the cache (bat cache --build) or remove the custom syntaxes/themes (bat cache --clear).
For more information, see:

https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions
```

After rebuilding the cache, delta started falling back to default syntax theme. Turns out delta needs to release a compatible version as well?

**Comment by dandavison** [comment]
Thanks! So if I'm understanding correctly, the problem here affects people (like me, and you) who have custom themes/syntaxes in a local cache which we are sharing with bat. Currently delta has copied/vendored code handling binary assets from bat . But I wonder if we can make use of some of the bat-as-a-library features mentioned in the release notes: https://github.com/sharkdp/bat/releases/tag/v0.19.0

![image](https://user-images.githubusercontent.com/52205/148867617-4fc1f1f4-ba54-48ed-a1a3-53f74d1c5106.png)

**Comment by dandavison** [comment]
The immediate fix here would be to use an older version of bat to create the custom theme for delta. The real fix is this unreleased delta PR https://github.com/dandavison/delta/pull/903 and the accompanying bat PR https://github.com/sharkdp/bat/pull/2030 which would need to be released first.

**Comment by michaelblyons** [comment]
...in April, they say. I'll keep my `bat` pinned to 0.18.3 for a while longer I suppose.

**Comment by dandavison** [comment]
Right. In the interim we could, in principle, update the binary assets in delta "manually" and apply any changes to our vendored bat code that are necessary, and release delta like that. Perhaps there are no code changes required -- it's just that when this issue was opened I decided to look into using bat as a library properly rather than doing the delta binary assets upgrade that I usually do at delta releases. It is time for a delta release -- I was trying to get https://github.com/dandavison/delta/pull/939 in.

**Comment by dandavison** [comment]
This is fixed in the latest delta version (the bat PR was released).
