### ISSUE TITLE
🚀 Merge `--list-syntax-themes` and `--show-syntax-themes` into `--list-themes`

### ISSUE THREAD

**Issue by kidonng** [dandavison/delta#896]
bat's `--list-themes` option does what delta's `--list-syntax-themes` and `--show-syntax-themes` do at the same time. Since delta is using bat under the hood, it would make sense the usage are aligned as well.

**Comment by dandavison** [comment]
Hi @kidonng, `delta` does not use `bat`. (`delta` does use the same syntax-highlighting themes and language grammar definitions that bat uses). It's deliberate that `delta` uses different terminology from bat. The reason is that `delta` works with both foreground and background colors, whereas `bat` only ever changes the foreground color of text for syntax highlighting. So `bat` only has one concept of "theme" -- the syntax highlighting theme -- whereas `delta` has two:
1. The syntax-highlighting theme, which `delta` calls `syntax-theme`
2. The choice of background colors, as well as decorations and other options.

Delta uses the term "theme" to refer to the overall choice of all colors-- foreground and background, as well as decorations.

This is also explained in the README: https://github.com/dandavison/delta#custom-themes

So I'll close this one, since I don't think there's anything to change. But let me know if any docs can be improved or if anythig about the theming or related commands can be improved.
