### ISSUE TITLE
Please avoid the re-release

### ISSUE THREAD

**Issue by navarroaxel** [dandavison/delta#91]
Please be careful when you re-release a version like `0.0.16` because some package systems use `sha256sum` to build the package for the Linux distro, so the re-release needs an upgrade in https://aur.archlinux.org/packages/git-delta

Maybe some other issues could happen when you do that.

The Linux kernel had an issue with the release `5.3.2` in October and they released the `5.3.3` with just 1 new commit making apologies about the noise: https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.3.3

Thanks 🙂

**Comment by dandavison** [comment]
Ah, of course, that was stupid of me. Thanks for the reminder, I won't do it again.

**Comment by dandavison** [comment]
Is the archlinux package in a correct state now?

**Comment by navarroaxel** [comment]
Yep, @Kr1ss-XD has upgraded the package.

**Comment by Kr1ss-XD** [comment]
Thx a lot for providing us your project, and releasing under a free license btw. I do use this software myself. :+1:

**Comment by hmble** [comment]
@Kr1ss-XD is it still necessary to include `clang` and `llvm` as dependency for installing this package ? 

Maybe we use build release strategy used by other tools like [`bat`] or [`ripgrep`].

**Comment by Kr1ss-XD** [comment]
As for a pre-built package, this would have to be `git-delta-bin` (btw I think there actually _is_ such a package in the AUR, iirc).
Otherwise, non '-bin' packages are built locally. I can't built `git-delta` in a clean chroot w/o `clang` and `llvm`. So yes, those are needed as build time dependencies.
`makepkg` will uninstall them after building the package if called w/ the `-r` flag.

**Comment by hmble** [comment]
Yes got it. Thanks

**Comment by dandavison** [comment]
Does the ArchLinux installer rely on any of the `.tar.gz` archive files that are hosted on the GitHub [releases page](https://github.com/dandavison/delta/releases/tag/0.0.18)? I was contemplating just hosting the executable directly, rather than wrapping it up in a compressed archive (since the compressed archive only serves to make it slightly more inconvenient for human users who want to download the executable).

**Comment by navarroaxel** [comment]
@dandavison no, the bin package use the `.deb` version.

**Comment by dandavison** [comment]
Thanks @navarroaxel.

**Comment by Kr1ss-XD** [comment]
Well there are basically two ways of packaging for the AUR. Default way is to have the package built locally in the users side. In the other hand, there may be a `...-bin` package with distributes the binary directly.
In case of `git-delta`, there is a binary package as well as one to be built locally from source to be chosen from.

**Comment by dandavison** [comment]
@Kr1ss-XD thanks, I'll keep the tarball in the releases tree. I'll mention it here again if I start also hosting the binaries directly in the releases tree.

**Comment by Kr1ss-XD** [comment]
Great, thank you !
