### ISSUE TITLE
Test for binary file diff passed when it should not have

### ISSUE THREAD

**Issue by dandavison** [dandavison/delta#95]
Why did the test in #94 pass at af84d5c when it should not have?

**Comment by wescande** [comment]
The test pass because [the source](https://github.com/dandavison/delta/blob/af84d5c7019f4481a6d64112d74e4eae727c4bd1/src/delta.rs#L68) is `Unknown`, so the output is [replicated direclty](https://github.com/dandavison/delta/blob/af84d5c7019f4481a6d64112d74e4eae727c4bd1/src/delta.rs#L72)

The test would have failed if there was no newline [here](https://github.com/dandavison/delta/blob/af84d5c7019f4481a6d64112d74e4eae727c4bd1/src/delta.rs#L859)

something like this:
```rust
   const BINARY_FILES_DIFFER: &str = "commit ad023698217b086f1bef934be62b4523c95f64d9 (HEAD -> master)
Author: Dan Davison <dandavison7@gmail.com>
Date:   Wed Feb 12 08:05:53 2020 -0600
    .
diff --git a/foo b/foo
new file mode 100644
index 0000000..b572921
Binary files /dev/null and b/foo differ
";
```
